<style>
  #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
      
	#panel {
        position: absolute;
        top: 5px;
        left: 50%;
        margin-left: -180px;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
      }
    </style>
<?php $this->headTitle('Ingresar Sitio - Actualizar Sitio');

//FORMULARIO
$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'sitio',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' );
$formLabel = $this->plugin ( 'formLabel' );

$sit_id = $form->get ( 'sit_id' );
$ciu_id = $form->get ( 'ciu_id' );
$est_id = $form->get ( 'est_id' );
$pai_id = $form->get ( 'pai_id' );

$pai_id_hidden = $form->get ( 'pai_id_hidden' );
$est_id_hidden = $form->get ( 'est_id_hidden' );
$ciu_id_hidden = $form->get ( 'ciu_id_hidden' );

$sit_descripcion = $form->get ( 'sit_descripcion' );
$sit_direccion = $form->get ( 'sit_direccion' );
$sit_sector = $form->get ( 'sit_sector' );
$sit_reference_number = $form->get ( 'sit_reference_number' );
$sit_estado = $form->get ( 'sit_estado' );
$sit_latitud = $form->get ( 'sit_latitud' );
$sit_longitud = $form->get ( 'sit_longitud' );

//EMPIEZA A ESCRIBIRSE EL FORMULARIO
echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $sit_id );
echo $this->formelementerrors ( $sit_id );

echo $this->formhidden ( $sit_estado );
echo $this->formelementerrors ( $sit_estado );

echo $this->formhidden ( $pai_id_hidden );
echo $this->formelementerrors ( $pai_id_hidden );
echo $this->formhidden ( $est_id_hidden );
echo $this->formelementerrors ( $est_id_hidden );
echo $this->formhidden ( $ciu_id_hidden );
echo $this->formelementerrors ( $ciu_id_hidden );

?>
<div class="panel panel-default">
	<div class="panel-heading panel-heading-txt">&nbsp;</div>
		<table width="100%" cellpadding="5">
			<tr>
				<td colspan="3">
					<br />
					<div width="50" valign="middle" class="icon-content"><img src="<?php echo $this->basepath() . '/img/png/pais_grande.png'?>" border="0" /></div>
					<div class="txt-icon-content">Ingresar un nuevo sitio<br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo sitio.</div>
					<div><br /><hr /></div>
				</td>
			</tr>
			<tr>
				<td>
				<?php echo $formLabel->openTag() . $pai_id->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formselect ( $pai_id ) );
					  echo html_entity_decode( $this->formelementerrors ( $pai_id ) ); 
				?>
				</td>
				
				<td>
				<?php echo $formLabel->openTag() . $est_id->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formselect ( $est_id ) );
					  echo html_entity_decode( $this->formelementerrors ( $est_id ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $ciu_id->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formselect ( $ciu_id ) );
					  echo html_entity_decode( $this->formelementerrors ( $ciu_id ) ); 
				?>
				</td>
				<td colspan="2">&nbsp;</td>
			</tr>
			<tr>
				<td>
				<?php echo $formLabel->openTag() . $sit_sector->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $sit_sector ) );
					  echo html_entity_decode( $this->formelementerrors ( $sit_sector ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $sit_direccion->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $sit_direccion ) );
					  echo html_entity_decode( $this->formelementerrors ( $sit_direccion ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $sit_descripcion->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $sit_descripcion ) );
					  echo html_entity_decode( $this->formelementerrors ( $sit_descripcion ) ); 
				?>
				</td>
			</tr>
			<tr>
				<td>
				<?php echo $formLabel->openTag() . $sit_reference_number->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $sit_reference_number ) );
					  echo html_entity_decode( $this->formelementerrors ( $sit_reference_number ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $sit_latitud->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $sit_latitud ) );
					  echo html_entity_decode( $this->formelementerrors ( $sit_latitud ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $sit_longitud->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $sit_longitud ) );
					  echo html_entity_decode( $this->formelementerrors ( $sit_longitud ) ); 
				?>
				</td>
			</tr>
			<tr>
				<td colspan="4" width="100%" height="500px;">
			      <input id="address" type="hidden" value="">
				<div id="map-canvas"></div>
				</td>
			</tr>
		</table>
		<br />
		<div><button type="button" id="addElement" class ="btn btn-primary">Agregar Componente</button></div>
		<div id=InputsWrapper></div>
		<div><br /><hr /></div>	
		<div align="center"> 
				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				<a href="<?php echo $this->url('parametros', array('controller' => 'sitio', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
			</div>	
		<div>&nbsp;</div>	
</div>
<?php echo $this->form()->closeTag(); ?>

<script>
function ubicacion(){
	var pais = $('#pai_id option:selected').text();
    var estado = $('#est_id option:selected').text();
    var ciudad = $('#ciu_id option:selected').text();
    var ubicacion = $('#sit_direccion').val();

    $("#address").val(ubicacion+', '+ciudad+', '+estado+', '+pais);
    codeAddress(17);
}

//FUNCION PARA CARGAR EL COMBO BOX DE ESTADOS EN BASE A UN PAIS SELECCIONADO
$("#pai_id").change(function() {
	if($('#pai_id').val() != '' && $('#pai_id').val() != null){
        $.ajax({
            url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'sucursalesAjax')) ?>",
            type: "POST",
            dataType: "json",
            data: "pais=" + $('#pai_id').val(),
            beforeSend: function() {
            	$("#est_id").html("");
            	$("#est_id").append('<option>Procesando, espere por favor...</option>');
            }
        }).done(function(estados) {
            $("#est_id").html("");
            $("#est_id").append('<option value = "null">-- Seleccione un estado --</option>');
            for (estado in estados) {
                $("#est_id").append('<option value="' + estado + '">' + estados[estado] + '</option>');
            }
            $("#est_id").prop("disabled", false);

            var pais = $('#pai_id option:selected').text();

            $("#address").val(pais);
            codeAddress(7);
            
        });

	}else{
		$("#est_id").prop("disabled", true);
	}
});

//FUNCION PARA CARGAR EL COMBO BOX DE CIUDADES EN BASE A UN ESTADO
$("#est_id").change(function() {
	if($('#est_id').val() != '' && $('#est_id').val() != null){
        $.ajax({
        	url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'ciudadesAjax')) ?>",
            type: "POST",
            dataType: "json",
            data: "estado=" + $('#est_id').val(),
            beforeSend: function() {
            	$("#ciu_id").html("");
            	$("#ciu_id").append('<option>Procesando, espere por favor...</option>');
            }
        }).done(function(ciudades) {
            $("#ciu_id").html("");
            $("#ciu_id").append('<option value = "null">-- Seleccione una ciudad --</option>');
            for (ciudad in ciudades) {
                $("#ciu_id").append('<option value="' + ciudad + '">' + ciudades[ciudad] + '</option>');
            }
            $("#ciu_id").prop("disabled", false);

            var pais = $('#pai_id option:selected').text();
            var estado = $('#est_id option:selected').text();

            $("#address").val(estado+', '+pais);
            codeAddress(12);
        });
	}else{
		$("#ciu_id").prop("disabled", true);
	}
});

$("#ciu_id").change(function() {
	if($('#ciu_id').val() != '' && $('#ciu_id').val() != null){
		
		var pais = $('#pai_id option:selected').text();
        var estado = $('#est_id option:selected').text();
        var ciudad = $('#ciu_id option:selected').text();

        $("#address").val(ciudad+', '+estado+', '+pais);
        codeAddress(15);
        
	};

});

//FUNCION PARA CARGAR LOS ESTADOS CUANDO EL FORMULARIO SEA DE ACTUALIZACION
$("#pai_id").ready(function() {
	if($('#pai_id').val() != '' && $('#pai_id').val() != null){
        $.ajax({
            url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'sucursalesAjax')) ?>",
            type: "POST",
            dataType: "json",
            data: "pais=" + $('#pai_id_hidden').val(),
            beforeSend: function() {
            	$("#est_id").html("");
            	$("#est_id").append('<option>Procesando, espere por favor...</option>');
            }
        }).done(function(estados) {
            $("#est_id").html("");
            $("#est_id").append('<option value = "null">-- Seleccione un estado --</option>');
            for (estado in estados) {
            	var selected = '';
				if($("#est_id_hidden").val() == estado){
					selected = 'selected="selected"';
				}else{
					selected = '';
				}
                
                $("#est_id").append('<option value="' + estado + '" ' + selected + '>' + estados[estado] + '</option>');
            }
            $("#est_id").prop("disabled", false);

            $("#est_id").ready(function() {
            	if($('#est_id').val() != '' && $('#est_id').val() != null){
                    $.ajax({
                    	url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'ciudadesAjax')) ?>",
                        type: "POST",
                        dataType: "json",
                        data: "estado=" + $('#est_id_hidden').val(),
                        beforeSend: function() {
                        	$("#ciu_id").html("");
                        	$("#ciu_id").append('<option>Procesando, espere por favor...</option>');
                        }
                    }).done(function(ciudades) {
                        $("#ciu_id").html("");
                        $("#ciu_id").append('<option value = "null">-- Seleccione una ciudad --</option>');
                        for (ciudad in ciudades) {
                        	var selected = '';
                        	if($("#est_id_hidden").val() == ciudad){
            					selected = 'selected="selected"';
            				}else{
            					selected = '';
            				}
            				
                            $("#ciu_id").append('<option value="' + ciudad + '" '+selected+'>' + ciudades[ciudad] + '</option>');
                        }
                        $("#ciu_id").prop("disabled", false);

                        $("#ciu_id").ready(function() {
                    		if($('#ciu_id').val() != '' && $('#ciu_id').val() != null){

								var lg = $('#sit_latitud').val();
								if(lg != '' && lg != null){
									//codeLatLng();
								}else{
	                    			var pais = $('#pai_id option:selected').text();
	                    	        var estado = $('#est_id option:selected').text();
	                    	        var ciudad = $('#ciu_id option:selected').text();
	                    	        var ubicacion = $('#sit_direccion').val();
	
	                    	        $("#address").val(ubicacion+', '+ciudad+', '+estado+', '+pais);
	                    	        codeAddress(17);
								}
                    	        
                    		};

                    	});

                    });
            	}else{
            		$("#ciu_id").prop("disabled", true);
            	}
            });

        });
	}else{
		$("#est_id").prop("disabled", true);
	}
});

</script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
<script>
	var map;
	var markers = [];
	var geocoder;
	
	function initialize() {

		geocoder = new google.maps.Geocoder();

		if($('#sit_latitud').val() == null || $('#sit_latitud').val == '' || $('#sit_latitud').val == ' '){
		    var lugar = new google.maps.LatLng(-0.1865943, -78.4305382);
		    var mapOptions = { zoom: 4, center: lugar };
		    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
		}else{
			map = new google.maps.Map(document.getElementById('map-canvas'));
			codeLatLng();
		}
		
		google.maps.event.addListener(map, 'click', function(e) {
				var total = totalMarkers();
				if(total == 0){
					addMarker(e.latLng, map);
					$('#sit_latitud').val(e.latLng.lat());
					$('#sit_longitud').val(e.latLng.lng());
				}else{
					deleteMarkers();
					addMarker(e.latLng, map);
					$('#sit_latitud').val(e.latLng.lat());
					$('#sit_longitud').val(e.latLng.lng());
				}
		  });
	}
	
	function addMarker(location, map) {
		  var marker = new google.maps.Marker({
		    position: location,
		    draggable: true,
		    map: map
		  });
		 markers.push(marker);
	
		 google.maps.event.addListener(marker, 'click', function(e) {
	
			 var infowindow = new google.maps.InfoWindow({
			      content: '<div>'+$('#sit_descripcion').val()+'</div>'+'<div>'+$('#sit_reference_number').val()+'</div>'
			  });
			 
			 infowindow.open(map,marker);
		 });
	
		 google.maps.event.addListener(marker, 'dragend', function (event) {
			    $('#sit_latitud').val(this.getPosition().lat());
				$('#sit_longitud').val(this.getPosition().lng());
			});
		 
		}
	
	function totalMarkers(){
		  return markers.length;
	}

	// Sets the map on all markers in the array.
	function setAllMap(map) {
	  for (var i = 0; i < markers.length; i++) {
	    markers[i].setMap(map);
	  }
	}

	// Removes the markers from the map, but keeps them in the array.
	function clearMarkers() {
	  setAllMap(null);
	}

	// Deletes all markers in the array by removing references to them.
	function deleteMarkers() {
	  clearMarkers();
	  markers = [];
	}

	function codeAddress(zoom) {

		map.setZoom(zoom);
		
		  var address = document.getElementById('address').value;
		  geocoder.geocode( { 'address': address}, function(results, status) {
		    if (status == google.maps.GeocoderStatus.OK) {
		    	map.setCenter(results[0].geometry.location);
		      /* var marker = new google.maps.Marker({
		          map: map,
		          position: results[0].geometry.location
		      }); */
		    } else {
		      //alert('Geocode was not successful for the following reason: ' + status);
		    }
		  });
	}

	function codeLatLng() {
		  var lat = parseFloat($('#sit_latitud').val());
		  var lng = parseFloat($('#sit_longitud').val());
		  
		  var latlng = new google.maps.LatLng(lat, lng);
		  geocoder.geocode({'latLng': latlng}, function(results, status) {
		    if (status == google.maps.GeocoderStatus.OK) {
		      if (results[1]) {
		    	map.setCenter(results[1].geometry.location);
		        map.setZoom(17);
		        marker = new google.maps.Marker({
		            position: latlng,
		            map: map
		        });
		        infowindow.setContent(results[1].formatted_address);
		        infowindow.open(map, marker);
		      } else {
		        alert('No results found');
		      }
		    } else {
		      alert('Geocoder failed due to: ' + status);
		    }
		  });
		}
	
	google.maps.event.addDomListener(window, 'load', initialize);
</script>
<script type="text/javascript">
$(document).ready(function() {

		//var MaxInputs       = 8; //maximum input boxes allowed
		var InputsWrapper   = $("#InputsWrapper"); //Input boxes wrapper ID

		var x = InputsWrapper.length; //initlal text box count
		var FieldCount=0; //to keep track of text box added

		$($("#addElement")).click(function (e)  //on add input button click
		{
/*
			$.ajax({
                url: "<?php //echo $this->url('contactos', array('controller' => 'index', 'action' => 'codigoCiudadTipo')) ?>",
                type: "POST",
                dataType: "json",
                data: "det_con_codigo_pais=" + $(element).val(),
                beforeSend: function() {
                	$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").html("");
                	$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option>Procesando, espere por favor...</option>');
                }
            }).done(function(ciudades) {
                $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").html("");
                $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option>-- Seleccione --</option>');
                var selected = '';
                for (ciudad in ciudades) {
					if($('#DETALLE_CONTACTO_oculto_'+data_group_id).val() == ciudad){
						selected = 'selected="selected"';
					}
	                
                    $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option value="' + ciudad + '" '+selected+'>' + ciudades[ciudad] + '</option>');
                }
                $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").prop("disabled", false);
                
            });

*/
		            FieldCount++; //text box added increment
		            //add input box
		            $(InputsWrapper).append('<div><input type="text" name="mytext[]" id="field_'+ FieldCount +'" value="Text '+ FieldCount +'"/><a href="#" class="removeclass">&times;</a></div>');
		            x++; //text box increment
		return false;
		});

		$("body").on("click",".removeclass", function(e){ //user click on remove text
		        if( x > 0 ) {
		        	$(this).parent('div').remove(); //remove text box
		            x--; //decrement textbox
		        }
		return false;
		}) 

    }
);
</script>