 <?php $this->headTitle('Listado de Sitios'); ?>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td>
			<div width="50" valign="middle" class="icon-content"><img src="<?php echo $this->basepath() . '/img/png/pais_grande.png'?>" border="0" /></div>
			<div class="txt-icon-content">Ingresar un nuevo sitio<br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo sitio.</div>
			<div><br /><hr /></div>
		</td>
	</tr>
</table>
 <div style="padding-bottom: 30px;">
     <a href="<?php echo $this->url('parametros', array('controller' => 'sitio', 'action'=>'ingresar'));?>" class="btn btn-primary">
     <img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar un nuevo registro</a>
 </div>
<div style=" padding-bottom: 100px;  ">
 <table class="table table-striped table-bordered table-hover" style="font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>&nbsp;</th>
     <th>Ciudad</th>
     <th>Descripci&oacute;n</th>
     <th>Direcci&oacute;n</th>
     <th>Sector</th>
     <th>N&uacute;mero de referencia</th>
     <th>Estado</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->sitios as $sitio) : ?>
 <tr>
 	 <td width="150">
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'sitio', 'action' => 'editar', 'id' => $sitio->getSit_id()))?>" title="Actualizar" alt="Actualizar">Editar</a> |
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'sitio', 'action' => 'eliminar', 'id' => $sitio->getSit_id()))?>" title="Eliminar" alt="Eliminar">Eliminar</a>
 	 </td>
 	 <td><?php echo $this->escapeHtml($sitio->getCiu_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($sitio->getSit_descripcion());?></td>
     <td><?php echo $this->escapeHtml($sitio->getSit_direccion());?></td>
     <td><?php echo $this->escapeHtml($sitio->getSit_sector());?></td>
     <td><?php echo $this->escapeHtml($sitio->getSit_reference_number());?></td>
     <td><?php echo ($sitio->getSit_estado() == 'A') ? 'Activo' : 'Inactivo';?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>