<div class="titulo-ventana"><i class="fa fa-gears fa-fw"></i> Par&aacute;metros - Listado de Sitios</div>
<hr class="hr-style" /> 

 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th width="7%">
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'sitio', 'action'=>'ingresar'));?>" class="btn btn-primary">
     	<i class="fa fa-plus-circle"></i> Nuevo</a>
 	 </th>
     <th>Ciudad</th>
     <th>Descripci&oacute;n</th>
     <th>Direcci&oacute;n</th>
     <th>Sector</th>
     <th>N&uacute;mero de referencia</th>
     <th>Estado</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->sitios as $sitio) : ?>
 <tr>
 	 <td style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('parametros', array('controller' => 'sitio', 'action' => 'editar', 'id' => $sitio->getSit_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('parametros', array('controller' => 'sitio', 'action' => 'eliminar', 'id' => $sitio->getSit_id()))?>" onclick="return eliminarRegistro('<?php echo $sitio->getSit_descripcion() ?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
 	 <td><?php echo $this->escapeHtml($sitio->getCiu_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($sitio->getSit_descripcion());?></td>
     <td><?php echo $this->escapeHtml($sitio->getSit_direccion());?></td>
     <td><?php echo $this->escapeHtml($sitio->getSit_sector());?></td>
     <td><?php echo $this->escapeHtml($sitio->getSit_reference_number());?></td>
     <td><?php echo ($sitio->getSit_estado() == 'A') ? 'Activo' : 'Inactivo';?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>