<style>
  #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
      
</style>
<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); 

$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'puntorecarga',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' )
->setAttribute ('class', 'form-horizontal');
$formLabel = $this->plugin ( 'formLabel' );

$pun_rec_id= $form->get ( 'pun_rec_id' );

$pun_rec_nombre			=	$form->get('pun_rec_nombre');
$pun_rec_ruc			=	$form->get('pun_rec_ruc');
//$pun_rec_codigo			=	$form->get('pun_rec_codigo');
$pun_rec_lat			=	$form->get('pun_rec_lat');
$pun_rec_lng			=	$form->get('pun_rec_lng');
$pun_rec_direccion		=	$form->get('pun_rec_direccion');
$pun_rec_observaciones	=	$form->get('pun_rec_observaciones');
$pun_rec_habilitado     =   $form->get('pun_rec_habilitado');
$pun_rec_clave          =   $form->get('pun_rec_clave');

$pun_rec_nombres        =   $form->get('pun_rec_nombres');
$pun_rec_apellidos      =   $form->get('pun_rec_apellidos');

echo $this->form ()->openTag ( $form );
echo $this->formhidden ( $pun_rec_id );
?>


<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span><?php echo $this->titulo ?> Punto de Recarga</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>

			<div class="box-content">
			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Ingrese la informaci&oacute;n solicitada. Todos los campos con * son obligatorios.</label>
        			</div>
    			</div>
	
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $pun_rec_ruc->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formtext ( $pun_rec_ruc ) );
                        echo html_entity_decode( $this->formelementerrors ( $pun_rec_ruc ) );
                        ?>
                    </div>
                </div>

    			<div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $pun_rec_nombre->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pun_rec_nombre ) );
            			echo html_entity_decode( $this->formelementerrors ( $pun_rec_nombre ) );
            			?>
            		</div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $pun_rec_nombres->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formtext ( $pun_rec_nombres ) );
                        echo html_entity_decode( $this->formelementerrors ( $pun_rec_nombres ) );
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $pun_rec_apellidos->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formtext ( $pun_rec_apellidos ) );
                        echo html_entity_decode( $this->formelementerrors ( $pun_rec_apellidos ) );
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $pun_rec_direccion->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formtext ( $pun_rec_direccion ) );
                        echo html_entity_decode( $this->formelementerrors ( $pun_rec_direccion ) );
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $pun_rec_habilitado->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formselect ( $pun_rec_habilitado ) );
                        echo html_entity_decode( $this->formelementerrors ( $pun_rec_habilitado ) );
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $pun_rec_clave->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formpassword ( $pun_rec_clave ) );
                        echo html_entity_decode( $this->formelementerrors ( $pun_rec_clave ) );
                        ?>
                    </div>
                </div>    

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $pun_rec_observaciones->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formtext ( $pun_rec_observaciones ) );
                        echo html_entity_decode( $this->formelementerrors ( $pun_rec_observaciones ) );
                        ?>
                    </div>
                </div>                



                <div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $pun_rec_lat->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pun_rec_lat ) );
            			echo html_entity_decode( $this->formelementerrors ( $pun_rec_lat ) );
            			?>
            		</div>
                </div>

                <div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $pun_rec_lng->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pun_rec_lng ) );
            			echo html_entity_decode( $this->formelementerrors ( $pun_rec_lng ) );
            			?>
            		</div>
                </div>
\
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1"><strong>Ubicaci&oacute;n*:</strong></div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div style="height: 500px;">
                            <input id="address" type="hidden" value="">
                            <div id="map-canvas"></div>
                        </div>
                    </div>
                </div>     

                <div class="row">
    				<div class="form-group col-md-12">
            		     <div align="center">
            				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				            <a href="<?php echo $this->url('parametros', array('controller' => 'puntorecarga', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
            			</div>	
        			</div>
    			</div>

			</div>
        </div>
    </div>
</div>



<?php echo $this->form()->closeTag(); ?>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
<script>
    var map;
    var markers = [];
    var geocoder;

    var latitud  = $('#pun_rec_lat').val();
    var longitud = $('#pun_rec_lng').val();

    function initialize() {
        geocoder = new google.maps.Geocoder();

        if(latitud=='' && longitud=='' )
            var lugar = new google.maps.LatLng(0.3668378562642896, -78.128708);
        else{
            var lugar = new google.maps.LatLng(latitud, longitud);

        }
        var mapOptions = { zoom: 16, center: lugar };
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
        addMarker(lugar, map);

        
        google.maps.event.addListener(map, 'click', function(e) {
                var total = totalMarkers();
                if(total == 0){
                    addMarker(e.latLng, map);
                    $('#pun_rec_lat').val(e.latLng.lat());
                    $('#pun_rec_lng').val(e.latLng.lng());
                }else{
                    deleteMarkers();
                    addMarker(e.latLng, map);
                    $('#pun_rec_lat').val(e.latLng.lat());
                    $('#pun_rec_lng').val(e.latLng.lng());
                }
          });
    }
    
    function addMarker(location, map) {
          var marker = new google.maps.Marker({
            position: location,
            draggable: true,
            map: map
          });
         markers.push(marker);
    
         google.maps.event.addListener(marker, 'click', function(e) {
    
             var infowindow = new google.maps.InfoWindow({
                  content: '<div>'+$('#pun_rec_nombre').val()+'</div>'
              });
             
             infowindow.open(map,marker);
         });
    
         google.maps.event.addListener(marker, 'dragend', function (event) {
                $('#pun_rec_lat').val(this.getPosition().lat());
                $('#pun_rec_lng').val(this.getPosition().lng());
            });
         
        }
    
    function totalMarkers(){
          return markers.length;
    }

    // Sets the map on all markers in the array.
    function setAllMap(map) {
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(map);
      }
    }

    // Removes the markers from the map, but keeps them in the array.
    function clearMarkers() {
      setAllMap(null);
    }

    // Deletes all markers in the array by removing references to them.
    function deleteMarkers() {
      clearMarkers();
      markers = [];
    }

    function codeAddress(zoom) {

        map.setZoom(zoom);
        
          var address = document.getElementById('address').value;
          geocoder.geocode( { 'address': address}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                map.setCenter(results[0].geometry.location);

            } else {
              //alert('Geocode was not successful for the following reason: ' + status);
            }
          });
    }

    function codeLatLng() {
          //var input = document.getElementById('latlng').value;
          //var latlngStr = input.split(',', 2);
          var lat = parseFloat($('#pun_rec_lat').val());
          var lng = parseFloat($('#pun_rec_lng').val());
          var latlng = new google.maps.LatLng(lat, lng);
          geocoder.geocode({'latLng': latlng}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
              if (results[1]) {
                map.setCenter(results[1].geometry.location);
                map.setZoom(17);
                marker = new google.maps.Marker({
                    position: latlng,
                    map: map
                });
                infowindow.setContent(results[1].formatted_address);
                infowindow.open(map, marker);
              } else {
                alert('No results found');
              }
            } else {
              alert('Geocoder failed due to: ' + status);
            }
          });
        }
    
    google.maps.event.addDomListener(window, 'load', initialize);
</script>