<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); 

$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'puntorecarga',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' )
->setAttribute ('class', 'form-horizontal');
$formLabel = $this->plugin ( 'formLabel' );

$pun_rec_id= $form->get ( 'pun_rec_id' );

$pun_rec_nombre			=	$form->get('pun_rec_nombre');
$pun_rec_ruc			=	$form->get('pun_rec_ruc');
//$pun_rec_codigo			=	$form->get('pun_rec_codigo');
$pun_rec_lat			=	$form->get('pun_rec_lat');
$pun_rec_lng			=	$form->get('pun_rec_lng');
$pun_rec_direccion		=	$form->get('pun_rec_direccion');
$pun_rec_observaciones	=	$form->get('pun_rec_observaciones');
$pun_rec_habilitado     =   $form->get('pun_rec_habilitado');
$pun_rec_clave          =   $form->get('pun_rec_clave');

echo $this->form ()->openTag ( $form );
echo $this->formhidden ( $pun_rec_id );
?>


<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span><?php echo $this->titulo ?> Punto de Recarga</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Ingrese la informaci&oacute;n solicitada. Todos los campos con * son obligatorios.</label>
        			</div>
    			</div>
	
    			<div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $pun_rec_nombre->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pun_rec_nombre ) );
            			echo html_entity_decode( $this->formelementerrors ( $pun_rec_nombre ) );
            			?>
            		</div>
                </div>

    			<div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $pun_rec_ruc->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pun_rec_ruc ) );
            			echo html_entity_decode( $this->formelementerrors ( $pun_rec_ruc ) );
            			?>
            		</div>
                </div>

                <div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $pun_rec_lat->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pun_rec_lat ) );
            			echo html_entity_decode( $this->formelementerrors ( $pun_rec_lat ) );
            			?>
            		</div>
                </div>

                <div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $pun_rec_lng->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pun_rec_lng ) );
            			echo html_entity_decode( $this->formelementerrors ( $pun_rec_lng ) );
            			?>
            		</div>
                </div>

                <div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $pun_rec_direccion->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pun_rec_direccion ) );
            			echo html_entity_decode( $this->formelementerrors ( $pun_rec_direccion ) );
            			?>
            		</div>
                </div>

                <div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $pun_rec_observaciones->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pun_rec_observaciones ) );
            			echo html_entity_decode( $this->formelementerrors ( $pun_rec_observaciones ) );
            			?>
            		</div>
                </div>                

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $pun_rec_habilitado->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formselect ( $pun_rec_habilitado ) );
                        echo html_entity_decode( $this->formelementerrors ( $pun_rec_habilitado ) );
                        ?>
                    </div>
                </div>        

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $pun_rec_clave->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formpassword ( $pun_rec_clave ) );
                        echo html_entity_decode( $this->formelementerrors ( $pun_rec_clave ) );
                        ?>
                    </div>
                </div>    

                <div class="row">
    				<div class="form-group col-md-12">
            		     <div align="center">
            				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				            <a href="<?php echo $this->url('parametros', array('controller' => 'puntorecarga', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
            			</div>	
        			</div>
    			</div>
			</div>
        </div>
    </div>
</div>



<?php echo $this->form()->closeTag(); ?>