<?php 
	//listado.phtml
?>

<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Recargas Por Verificar</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                    <th>Acciones</th>
                    <th>Fecha</th>
                    <th>Punto de Recarga</th>
                    <th>Usuario</th>
                    <th>Valor</th>
                    
                 </tr>
                 </thead>
                 <tbody>

                 <?php 
                 foreach ($this->cargas as $carga) : ?>
                 <tr>
                    <td class="dataTableIcons">
                        <a class="fa-lg" onclick="return confirm('Está seguro de que desea aprobar esta recarga? Si acepta, se registrará en el sistema del municipio')" href="<?php echo $this->url('parametros', array('controller' => 'puntorecarga', 'action' => 'aceptar_carga', 'id' => $carga['car_id']))?>"><i class="fa fa-check "></i> Aprobar</a>
                    </td>
                    <td><?php  echo $this->escapeHtml($carga['car_fecha']);?></td>
                    <td><?php  echo $this->escapeHtml($carga['pun_rec_nombre']);?></td>
                    <td><?php  echo $this->escapeHtml($carga['usu_nombre']).' '.$this->escapeHtml($carga['usu_apellido']);?></td>
                    <td>$<?php  echo $this->escapeHtml($carga['car_valor']);?></td>

                 </tr>
                 <?php endforeach; ?>

                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>