<style>
  #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
      
</style>
<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); 

$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'parqueadero',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' )
->setAttribute ('class', 'form-horizontal');
$formLabel = $this->plugin ( 'formLabel' );

$par_id= $form->get ( 'par_id' );
$par_estado = $form->get ( 'par_estado' );
$par_codigo = $form->get ( 'par_codigo' );
$par_tipo = $form->get ( 'par_tipo' );
$sec_id = $form->get ( 'sec_id' );
$par_latitud = $form->get('par_latitud');
$par_longitud = $form->get('par_longitud');
$par_cal_principal = $form->get('par_cal_principal');
$par_cal_secundaria = $form->get('par_cal_secundaria');

//$date = new Fecha();
echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $par_codigo );
echo $this->formelementerrors ( $par_codigo );

?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span><?php echo $this->titulo ?> parqueadero</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Ingrese la informaci&oacute;n solicitada. Todos los campos con * son obligatorios.</label>
        			</div>
    			</div>
    			<div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                		echo $formLabel->openTag() . $sec_id->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formselect ( $sec_id ) );
            			echo html_entity_decode( $this->formelementerrors ( $sec_id ) );
            			?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $par_id->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $par_id ) );
					    echo html_entity_decode( $this->formelementerrors ( $par_id ) ); 
            			?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $par_estado->getLabel() . $formLabel->closeTag();
                	    ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                	   <?php 
                		echo html_entity_decode( $this->formselect ( $par_estado ) );
					    echo html_entity_decode( $this->formelementerrors ( $par_estado ) );   
                	   ?>
            		</div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                        echo $formLabel->openTag() . $par_tipo->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                       <?php 
                        echo html_entity_decode( $this->formselect ( $par_tipo ) );
                        echo html_entity_decode( $this->formelementerrors ( $par_tipo ) );   
                       ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                        echo $formLabel->openTag() . $par_cal_principal->getLabel() . $formLabel->closeTag();
                       ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formselect ( $par_cal_principal ) );
                        echo html_entity_decode( $this->formelementerrors ( $par_cal_principal ) );
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                        echo $formLabel->openTag() . $par_cal_secundaria->getLabel() . $formLabel->closeTag();
                       ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formselect ( $par_cal_secundaria ) );
                        echo html_entity_decode( $this->formelementerrors ( $par_cal_secundaria ) );
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                        echo $formLabel->openTag() . $par_latitud->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                       <?php 
                        echo html_entity_decode( $this->formtext ( $par_latitud ) );
                        echo html_entity_decode( $this->formelementerrors ( $par_latitud ) );   
                       ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                        echo $formLabel->openTag() . $par_longitud->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                       <?php 
                        echo html_entity_decode( $this->formtext ( $par_longitud ) );
                        echo html_entity_decode( $this->formelementerrors ( $par_longitud ) );   
                       ?>
                    </div>
                </div>

               <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1"><strong>Ubicaci&oacute;n*:</strong></div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div style="height: 500px;">
                            <input id="address" type="hidden" value="">
                            <div id="map-canvas"></div>
                        </div>
                    </div>
                </div>                
                

                <div class="row">
    				<div class="form-group col-md-12">
            		     <div align="center">
            				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				            <a href="<?php echo $this->url('parametros', array('controller' => 'parqueadero', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
            			</div>	
        			</div>
    			</div>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>

<script>
    var map;
    var markers = [];
    var geocoder;


    var latitud  = $('#par_latitud').val();
    var longitud = $('#par_longitud').val();

    function initialize() {
        geocoder = new google.maps.Geocoder();
        
        if(latitud=='' && longitud=='' )
            var lugar = new google.maps.LatLng(0.3668378562642896, -78.128708);
        else{
            var lugar = new google.maps.LatLng(latitud, longitud);
        }
        
        var mapOptions = { zoom: 16, center: lugar };
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    
        addMarker(lugar, map);

        google.maps.event.addListener(map, 'click', function(e) {
                var total = totalMarkers();
                if(total == 0){
                    addMarker(e.latLng, map);
                    $('#par_latitud').val(e.latLng.lat());
                    $('#par_longitud').val(e.latLng.lng());
                }else{
                    deleteMarkers();
                    addMarker(e.latLng, map);
                    $('#par_latitud').val(e.latLng.lat());
                    $('#par_longitud').val(e.latLng.lng());
                }
          });
    }
    
    function addMarker(location, map) {
          var marker = new google.maps.Marker({
            position: location,
            draggable: true,
            map: map
          });
         markers.push(marker);
    
         google.maps.event.addListener(marker, 'click', function(e) {
    
             var infowindow = new google.maps.InfoWindow({
                  content: '<div>'+$('#par_id').val()+'</div>'+'<div>'+$('#sec_ubicacion').val()+'</div>'
              });
             
             infowindow.open(map,marker);
         });
    
         google.maps.event.addListener(marker, 'dragend', function (event) {
                $('#par_latitud').val(this.getPosition().lat());
                $('#par_longitud').val(this.getPosition().lng());
            });
         
        }
    
    function totalMarkers(){
          return markers.length;
    }

    // Sets the map on all markers in the array.
    function setAllMap(map) {
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(map);
      }
    }

    // Removes the markers from the map, but keeps them in the array.
    function clearMarkers() {
      setAllMap(null);
    }

    // Deletes all markers in the array by removing references to them.
    function deleteMarkers() {
      clearMarkers();
      markers = [];
    }

    function codeAddress(zoom) {

        map.setZoom(zoom);
        
          var address = document.getElementById('address').value;
          geocoder.geocode( { 'address': address}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                map.setCenter(results[0].geometry.location);

            } else {
              //alert('Geocode was not successful for the following reason: ' + status);
            }
          });
    }

    function codeLatLng() {
          //var input = document.getElementById('latlng').value;
          //var latlngStr = input.split(',', 2);
          var lat = parseFloat($('#par_latitud').val());
          var lng = parseFloat($('#par_longitud').val());
          var latlng = new google.maps.LatLng(lat, lng);
          geocoder.geocode({'latLng': latlng}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
              if (results[1]) {
                map.setCenter(results[1].geometry.location);
                map.setZoom(17);
                marker = new google.maps.Marker({
                    position: latlng,
                    map: map
                });
                infowindow.setContent(results[1].formatted_address);
                infowindow.open(map, marker);
              } else {
                alert('No results found');
              }
            } else {
              alert('Geocoder failed due to: ' + status);
            }
          });
        }
    
    google.maps.event.addDomListener(window, 'load', initialize);
</script>