<div class="titulo-ventana"><i class="fa fa-gears fa-fw"></i> Par&aacute;metros - Listado de Parqueaderos</div>
<hr class="hr-style" /> 

 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th width="7%">
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'parqueadero', 'action'=>'ingresar'));?>" class="btn btn-primary">
     	<i class="fa fa-plus-circle"></i> Nuevo</a>
 	 </th>
 	 <th>Parqueadero</th>
     <th>Sector</th>
     <th>Estado</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->parqueadero as $parqueadero) : ?>
 <tr>
 	 <td style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('parametros', array('controller' => 'parqueadero', 'action' => 'editar', 'id' => $parqueadero->getPar_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('parametros', array('controller' => 'parqueadero', 'action' => 'eliminar', 'id' => $parqueadero->getPar_id()))?>" onclick="return eliminarRegistro('<?php echo $parqueadero->getPar_id() ?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
	 <td><?php echo $this->escapeHtml($parqueadero->getPar_id());?></td>
 	 <td><?php echo $this->escapeHtml($parqueadero->getSec_nombre());?></td>
     <td>
     	<?php 
     	if(strtoupper($parqueadero->getPar_estado()) == 'D'):
     		echo 'Disponible';
     	else:
     		echo 'Ocupado';
     	endif;
     	?>
     </td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>