<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Parqueaderos</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                 	 <th width="7%">
                 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'parqueadero', 'action'=>'ingresar'));?>" class="btn btn-primary">
                     	<i class="fa fa-plus-circle"></i> Nuevo</a>
                 	 </th>
                 	 <th>Parqueadero</th>
                     <th>Sector</th>
                     <th class="hidden-xs">Estado</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                 foreach ($this->parqueadero as $parqueadero) : ?>
                 <tr>
                 	 <td class="dataTableIcons">
                 	 	<a class="fa-lg" href="<?php echo $this->url('parametros', array('controller' => 'parqueadero', 'action' => 'editar', 'id' => $parqueadero->getPar_id()))?>"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp;
                 	 	<a class="fa-lg" href="<?php echo $this->url('parametros', array('controller' => 'parqueadero', 'action' => 'eliminar', 'id' => $parqueadero->getPar_id()))?>" onclick="return eliminarRegistro('<?php echo $parqueadero->getPar_id() ?>');"><i class="fa fa-trash-o"></i></a>
                 	 </td>
                	 <td><?php echo $this->escapeHtml($parqueadero->getPar_id());?></td>
                 	 <td><?php echo $this->escapeHtml($parqueadero->getSec_nombre());?></td>
                     <td class="hidden-xs">
                     	<?php 
                     	if(strtoupper($parqueadero->getPar_estado()) == 'D'):
                     		echo 'Disponible';
                     	else:
                     		echo 'Ocupado';
                     	endif;
                     	?>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>