<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); 

$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'calle',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' )
->setAttribute ('class', 'form-horizontal');
$formLabel = $this->plugin ( 'formLabel' );

$cal_id= $form->get ( 'cal_id' );

$cal_nombre		=	$form->get('cal_nombre');
$cal_codigo     =   $form->get('cal_codigo');


echo $this->form ()->openTag ( $form );
echo $this->formhidden ( $cal_id );
?>


<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span><?php echo $this->titulo ?> Calle</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Ingrese la informaci&oacute;n solicitada. Todos los campos con * son obligatorios.</label>
        			</div>
    			</div>
	
    			<div class="form-group">
	                <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
	                    <?php  
	                		echo $formLabel->openTag() . $cal_codigo->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $cal_codigo ) );
            			echo html_entity_decode( $this->formelementerrors ( $cal_codigo ) );
            			?>
            		</div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $cal_nombre->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formtext ( $cal_nombre ) );
                        echo html_entity_decode( $this->formelementerrors ( $cal_nombre ) );
                        ?>
                    </div>
                </div>                
          

                <div class="row">
    				<div class="form-group col-md-12">
            		     <div align="center">
            				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				            <a href="<?php echo $this->url('parametros', array('controller' => 'puntorecarga', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
            			</div>	
        			</div>
    			</div>
			</div>
        </div>
    </div>
</div>



<?php echo $this->form()->closeTag(); ?>