<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Calles</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                 	 <th width="7%">
                 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'calle', 'action'=>'ingresar'));?>" class="btn btn-primary">
                     	<i class="fa fa-plus-circle"></i> Nuevo</a>
                 	 </th>
                     <th>Id</th>
                     <th>Código</th>
                     <th>Nombre</th>
                 </tr>
                 </thead>
                 <tbody>
                    <?php foreach ($this->calles as $calle) : ?>
                    <tr>
                        <td class="dataTableIcons">
                            <a class="fa-lg" href="<?php echo $this->url('parametros', array('controller' => 'calle', 'action' => 'editar', 'id' => $calle->getCal_id()))?>"><i class="fa fa-pencil"></i></a>
                        </td>
                        <td><?php echo $this->escapeHtml($calle->getCal_id());?></td>
                        <td><?php echo $this->escapeHtml($calle->getCal_codigo());?></td>
                        <td><?php echo $this->escapeHtml($calle->getCal_nombre());?></td>
                    </tr>
                    <?php endforeach; ?>
                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>

	