<div class="titulo-ventana">Monitoreo Sitio - <?php echo $this->sitio->getSit_descripcion()?></div>
<hr style="margin-bottom: 20px; margin-top: 0px;" />

<div style="float: left; padding-right: 20px; border-right: 1px solid #eeeeee; width: 25%;">

	<div style="padding-left: 10px; padding-bottom: 5px;"><b>N&uacute;mero de Referencia:</b> <?php echo $this->sitio->getSit_reference_number()?></div>
	<div style="padding-left: 10px; padding-bottom: 5px;"><b>Pa&iacute;s/Estado</b> <?php echo $this->sitio->getPai_nombre_es() . ' - ' . $this->sitio->getEst_nombre_es() ?></div>
	<div style="padding-left: 10px; padding-bottom: 5px;"><b>Ciudad:</b> <?php echo $this->sitio->getCiu_nombre_es() ?></div>
	<div style="padding-left: 10px;"><b>Direcci&oacute;n:</b> <?php echo $this->sitio->getSit_direccion()?></div>

<hr />

<div style="padding-left: 10px;"><b>Componentes:</b></div>
<br />
<div style="padding-left: 10px;">
   <?php
   
   		if(count($this->componentes[$this->sitio->getSit_id()])>0):
   			foreach ($this->componentes[$this->sitio->getSit_id()] as $componente):
   		?>	
   				<div style="color: #578fc0; ">- <?php echo $componente['com_descripcion']; ?> </div>
   				<div class="ip-local"><b>IP Local:</b> <?php echo $componente['com_ip_local']; ?> </div>
   				<div style="padding-left: 20px; padding-top: 5px;"><?php if ( $componente['com_estado'] == 'I' ): ?>
		   				<div class="circulo-rojo">&nbsp;</div>
		  				<div class="circulo-rojo">&nbsp;</div>
		  				<div class="circulo-rojo">&nbsp;</div>
		  				<div style="clear: both;"></div>
	   				<?php elseif( $componente['com_estado'] == 'A' ): ?>
		   				<div class="circulo-verde">&nbsp;</div>
		  				<div class="circulo-verde">&nbsp;</div>
		  				<div class="circulo-verde">&nbsp;</div>
		  				<div class="circulo-verde">&nbsp;</div>
		  				<div class="circulo-verde">&nbsp;</div>
		  				<div style="clear: both;"></div>
	   				<?php endif;?>
   				</div>
   				<div class="ulitma-respuesta"><b>&Uacute;ltima revisi&oacute;n:</b> <?php echo $componente['com_ultima_respuesta']; ?> </div>
   				<hr style="border-top: dashed 1px #aeaaaa; " />
   			<?php 
   			endforeach;
   		else:
   				echo "<span style='color:red;'>No tiene componentes asociados</span>";
   		endif;
  	?>
  	</div>
 </div>
 <div style="float: left; width: 75%; padding-left: 20px; ">
 <div id="map-canvas" style="height: 300px;"></div>
 <div><hr /></div>
 <div>
 	<?php for ($i=0; $i<6; $i++): ?>
 		<div style="background-color: #ffffff; float: left; margin: 4px; border: 1px solid #eeeeee; ">
 			<img src="<?php echo $this->basepath() . '/img/png/camara.png';?>" border="0" style="margin: 4px;" />
 		</div>
    <?php endfor;?>
 </div>
 </div>
 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
<script>

	var map;
	var geocoder;
	var latitudSite = parseFloat(<?php echo $this->sitio->getSit_latitud() ?>);
	var longitudSite = parseFloat(<?php echo $this->sitio->getSit_longitud() ?>);
	
	function initialize() {

		geocoder = new google.maps.Geocoder();
	    var lugar = new google.maps.LatLng(latitudSite, longitudSite);
	    map = new google.maps.Map(document.getElementById('map-canvas'));
	    codeLatLng();
	}
	

	function codeLatLng() {
		  var latlng = new google.maps.LatLng(latitudSite, longitudSite);
		  geocoder.geocode({'latLng': latlng}, function(results, status) {
		    if (status == google.maps.GeocoderStatus.OK) {
		      if (results[1]) {
		    	map.setCenter(results[1].geometry.location);
		        map.setZoom(17);
		        marker = new google.maps.Marker({
		            position: latlng,
		            map: map
		        });
		        infowindow.setContent(results[1].formatted_address);
		        infowindow.open(map, marker);
		      } else {
		        alert('No results found');
		      }
		    } else {
		      alert('Geocoder failed due to: ' + status);
		    }
		  });
		}
	
	google.maps.event.addDomListener(window, 'load', initialize);
</script>