<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Ventas</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                 	 <th>Nombre</th>
                 	 <th>Apellido</th>
                     <th>Usuario</th>
                     <th>Telefono</th>
                     <th>Valor</th>
                     <th>Fecha Registro</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                 $suma = 0;
                 foreach ($this->compras as $transaccion) : ?>
                 <tr>
                     <td class="dataTableIcons">
                 	 	<pre>
                            <?php print_r($transaccion); ?>
                        </pre>
                 	 </td>
                     <td></td>
                     <td></td>
                     <td></td>
                     <td></td>
                     <td></td>  

                 </tr>
                 
                 <?php endforeach; ?>
                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>