<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Compras de Parqueo</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                     <th>Ciudad</th>
                     <th>Sector</th>
                 	 <th>Cliente</th>
                 	 <th>Valor</th>
                     <th>Saldo</th>
                     <th>Fecha de compra</th>
                     <th>Placa</th>
                     <th>N&uacute;mero de horas</th>
                     <th>Valor Hora</th>
                     <th>Total Transacci&oacute;n</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                 $suma = 0;
                 foreach ($this->transaccion as $transaccion) : ?>
                 <tr>
                     <td style="height: 28px;"><?php echo $this->escapeHtml($transaccion->getCiu_nombre_es());?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getSec_nombre());?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getUsu_nombre() . ' ' . $transaccion->getUsu_apellido());?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getTra_valor());?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getTra_saldo());?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getTra_fecha());?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getAut_placa());?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getLog_par_horas_parqueo());?></td>
                     <td><?php echo '$ ' . $this->escapeHtml($transaccion->getSec_valor_hora());?></td>
                     <td><?php echo '$ ' . $transaccion->getLog_par_horas_parqueo() * $transaccion->getSec_valor_hora() ?></td>
                 </tr>
                 <?php 
                    $sumaHoras += $transaccion->getLog_par_horas_parqueo(); 
                    $sumaValorHora += $transaccion->getSec_valor_hora();
                    $sumaTotal += $transaccion->getLog_par_horas_parqueo() * $transaccion->getSec_valor_hora();
                 ?>
                 <?php endforeach; ?>
                 
                 <tr>
                     <td style="height: 28px;">&nbsp;</td>
                     <td style="border-left: 0px solid;">&nbsp;</td>
                     <td style="border-left: 0px solid;">&nbsp;</td>
                     <td style="border-left: 0px solid;">&nbsp;</td>
                     <td style="border-left: 0px solid;">&nbsp;</td>
                     <td style="border-left: 0px solid;">&nbsp;</td>
                     <td class="success" style="font-size: 14px; font-weight: 700; border: 0px solid;"><?php echo 'Total Horas Pagadas: ' ?></td>
                     <td class="success" style="border-left: 0px solid; font-size: 14px; font-weight: 700; border: 0px solid;"><?php echo $sumaHoras ?></td>
                     <td class="success" style="font-size: 14px; font-weight: 700; border: 0px solid;"><?php echo 'Valor Total: ' ?></td>
                     <td class="success" style="border-left: 0px solid; font-size: 14px; font-weight: 700; border: 0px solid;"><?php echo '$ ' . $sumaTotal ?></td>
                 </tr>
                 
                 
                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>