<style>
  #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
      
	#panel {
        position: absolute;
        top: 5px;
        left: 50%;
        margin-left: -180px;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
      }
    </style>
<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion);

$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'sector',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' )
->setAttribute ('class', 'form-horizontal');
$formLabel = $this->plugin ( 'formLabel' );

$sec_id = $form->get ( 'sec_id' );
$sec_nombre = $form->get ( 'sec_nombre' );
$sec_latitud = $form->get ( 'sec_latitud' );
$sec_longitud = $form->get ( 'sec_longitud' );
$ciu_id = $form->get ( 'ciu_id' );
$pai_id = $form->get ( 'pai_id' );
$est_id = $form->get ( 'est_id' );
$sec_ubicacion = $form->get ( 'sec_ubicacion' );


//$date = new Fecha();
echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $sec_id );
echo $this->formelementerrors ( $sec_id );

echo $this->formhidden ( $form->get ( 'pai_id_hidden' ) );
echo $this->formhidden ( $form->get ( 'est_id_hidden' ) );
echo $this->formhidden ( $form->get ( 'ciu_id_hidden' ) );

?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span><?php echo $this->titulo ?> sector</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Ingrese la informaci&oacute;n solicitada. Todos los campos con * son obligatorios.</label>
        			</div>
    			</div>
    			<div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                		echo $formLabel->openTag() . $pai_id->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formselect ( $pai_id ) );
					    echo html_entity_decode( $this->formelementerrors ( $pai_id ) ); 
            			?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $est_id->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formselect ( $est_id ) );
					    echo html_entity_decode( $this->formelementerrors ( $est_id ) );
            			?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $ciu_id->getLabel() . $formLabel->closeTag();
                	    ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                	   <?php 
                		echo html_entity_decode( $this->formselect ( $ciu_id ) );
					    echo html_entity_decode( $this->formelementerrors ( $ciu_id ) );   
                	   ?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $sec_nombre->getLabel() . $formLabel->closeTag();
                	    ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                		<?php 
                		echo html_entity_decode( $this->formtext ( $sec_nombre ) );
					    echo html_entity_decode( $this->formelementerrors ( $sec_nombre ) );     
                		?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                        echo $formLabel->openTag() . $sec_ubicacion->getLabel() . $formLabel->closeTag();
                	    ?>
                    </div>
                    <div class="col-xs-8 col-sm-11 col-md-7 col-lg-7">
                		<?php 
                		echo html_entity_decode( $this->formtext ( $sec_ubicacion ) );
					    echo html_entity_decode( $this->formelementerrors ( $sec_ubicacion ) );    
                		?>
            		</div>
            		<div class="col-xs-4 col-sm-1 col-md-1 col-lg-1">
            		  <input type="button" value="Buscar" class="btn btn-primary" onclick="ubicacion();" style="margin-left: 5px;">
            		</div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $sec_latitud->getLabel() . $formLabel->closeTag();
                	    ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                		<?php 
                		echo html_entity_decode( $this->formtext ( $sec_latitud ) );
					    echo html_entity_decode( $this->formelementerrors ( $sec_latitud ) );     
                		?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $sec_longitud->getLabel() . $formLabel->closeTag();
                	    ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                		<?php 
                		echo html_entity_decode( $this->formtext ( $sec_longitud ) );
					    echo html_entity_decode( $this->formelementerrors ( $sec_longitud ) );   
                		?>
            		</div>
                </div>
                
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1"><strong>Ubicaci&oacute;n*:</strong></div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div style="height: 500px;">
                            <input id="address" type="hidden" value="">
                        	<div id="map-canvas"></div>
                        </div>
                    </div>
                </div>

                <div class="row">
    				<div class="form-group col-md-12">
            		     <div align="center">
            				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				            <a href="<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
            			</div>	
        			</div>
    			</div>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<script>
function ubicacion(){
	var pais = $('#pai_id option:selected').text();
    var estado = $('#est_id option:selected').text();
    var ciudad = $('#ciu_id option:selected').text();
    var ubicacion = $('#sec_ubicacion').val();

    $("#address").val(ubicacion+', '+ciudad+', '+estado+', '+pais);
    codeAddress(17);
}

//FUNCION PARA CARGAR EL COMBO BOX DE ESTADOS EN BASE A UN PAIS SELECCIONADO
$("#pai_id").change(function() {
	if($('#pai_id').val() != '' && $('#pai_id').val() != null){
        $.ajax({
            url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'sucursalesAjax')) ?>",
            type: "POST",
            dataType: "json",
            data: "pais=" + $('#pai_id').val(),
            beforeSend: function() {
            	$("#est_id").html("");
            	$("#est_id").append('<option>Procesando, espere por favor...</option>');
            }
        }).done(function(estados) {
            $("#est_id").html("");
            $("#est_id").append('<option value = "null">-- Seleccione un estado --</option>');
            for (estado in estados) {
                $("#est_id").append('<option value="' + estado + '">' + estados[estado] + '</option>');
            }
            $("#est_id").prop("disabled", false);

            var pais = $('#pai_id option:selected').text();

            $("#address").val(pais);
            codeAddress(7);
            
        });

	}else{
		$("#est_id").prop("disabled", true);
	}
});

//FUNCION PARA CARGAR EL COMBO BOX DE CIUDADES EN BASE A UN ESTADO
$("#est_id").change(function() {
	if($('#est_id').val() != '' && $('#est_id').val() != null){
        $.ajax({
        	url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'ciudadesAjax')) ?>",
            type: "POST",
            dataType: "json",
            data: "estado=" + $('#est_id').val(),
            beforeSend: function() {
            	$("#ciu_id").html("");
            	$("#ciu_id").append('<option>Procesando, espere por favor...</option>');
            }
        }).done(function(ciudades) {
            $("#ciu_id").html("");
            $("#ciu_id").append('<option value = "null">-- Seleccione una ciudad --</option>');
            for (ciudad in ciudades) {
                $("#ciu_id").append('<option value="' + ciudad + '">' + ciudades[ciudad] + '</option>');
            }
            $("#ciu_id").prop("disabled", false);

            var pais = $('#pai_id option:selected').text();
            var estado = $('#est_id option:selected').text();

            $("#address").val(estado+', '+pais);
            codeAddress(12);
        });
	}else{
		$("#ciu_id").prop("disabled", true);
	}
});

$("#ciu_id").change(function() {
	if($('#ciu_id').val() != '' && $('#ciu_id').val() != null){
		
		var pais = $('#pai_id option:selected').text();
        var estado = $('#est_id option:selected').text();
        var ciudad = $('#ciu_id option:selected').text();

        $("#address").val(ciudad+', '+estado+', '+pais);
        codeAddress(15);
        
	};

});

//FUNCION PARA CARGAR LOS ESTADOS CUANDO EL FORMULARIO SEA DE ACTUALIZACION
$("#pai_id").ready(function() {
	if($('#pai_id').val() != '' && $('#pai_id').val() != null){
        $.ajax({
            url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'sucursalesAjax')) ?>",
            type: "POST",
            dataType: "json",
            data: "pais=" + $('#pai_id_hidden').val(),
            beforeSend: function() {
            	$("#est_id").html("");
            	$("#est_id").append('<option>Procesando, espere por favor...</option>');
            }
        }).done(function(estados) {
            $("#est_id").html("");
            $("#est_id").append('<option value = "null">-- Seleccione un estado --</option>');
            for (estado in estados) {
            	var selected = '';
				if($("#est_id_hidden").val() == estado){
					selected = 'selected="selected"';
				}else{
					selected = '';
				}
                
                $("#est_id").append('<option value="' + estado + '" ' + selected + '>' + estados[estado] + '</option>');
            }
            $("#est_id").prop("disabled", false);

            $("#est_id").ready(function() {
            	if($('#est_id').val() != '' && $('#est_id').val() != null){
                    $.ajax({
                    	url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'ciudadesAjax')) ?>",
                        type: "POST",
                        dataType: "json",
                        data: "estado=" + $('#est_id_hidden').val(),
                        beforeSend: function() {
                        	$("#ciu_id").html("");
                        	$("#ciu_id").append('<option>Procesando, espere por favor...</option>');
                        }
                    }).done(function(ciudades) {
                        $("#ciu_id").html("");
                        $("#ciu_id").append('<option value = "null">-- Seleccione una ciudad --</option>');
                        for (ciudad in ciudades) {
                        	var selected = '';
                        	if($("#est_id_hidden").val() == ciudad){
            					selected = 'selected="selected"';
            				}else{
            					selected = '';
            				}
            				
                            $("#ciu_id").append('<option value="' + ciudad + '" '+selected+'>' + ciudades[ciudad] + '</option>');
                        }
                        $("#ciu_id").prop("disabled", false);

                        $("#ciu_id").ready(function() {
                    		if($('#ciu_id').val() != '' && $('#ciu_id').val() != null){

								var lg = $('#sec_latitud').val();
								if(lg != '' && lg != null){
									codeLatLng();
								}else{
	                    			var pais = $('#pai_id option:selected').text();
	                    	        var estado = $('#est_id option:selected').text();
	                    	        var ciudad = $('#ciu_id option:selected').text();
	                    	        var ubicacion = $('#sec_ubicacion').val();
	
	                    	        $("#address").val(ubicacion+', '+ciudad+', '+estado+', '+pais);
	                    	        codeAddress(17);
								}
                    	        
                    		};

                    	});

                    });
            	}else{
            		$("#ciu_id").prop("disabled", true);
            	}
            });

        });
	}else{
		$("#est_id").prop("disabled", true);
	}
});

</script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
<script>
	var map;
	var markers = [];
	var geocoder;
	
	function initialize() {

		geocoder = new google.maps.Geocoder();
	    var lugar = new google.maps.LatLng(-0.1865943, -78.4305382);
	    var mapOptions = { zoom: 4, center: lugar };
	    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
	
		google.maps.event.addListener(map, 'click', function(e) {
				var total = totalMarkers();
				if(total == 0){
					addMarker(e.latLng, map);
					$('#sec_latitud').val(e.latLng.lat());
					$('#sec_longitud').val(e.latLng.lng());
				}else{
					deleteMarkers();
					addMarker(e.latLng, map);
					$('#sec_latitud').val(e.latLng.lat());
					$('#sec_longitud').val(e.latLng.lng());
				}
		  });
	}
	
	function addMarker(location, map) {
		  var marker = new google.maps.Marker({
		    position: location,
		    draggable: true,
		    map: map
		  });
		 markers.push(marker);
	
		 google.maps.event.addListener(marker, 'click', function(e) {
	
			 var infowindow = new google.maps.InfoWindow({
			      content: '<div>'+$('#sec_nombre').val()+'</div>'+'<div>'+$('#sec_ubicacion').val()+'</div>'
			  });
			 
			 infowindow.open(map,marker);
		 });
	
		 google.maps.event.addListener(marker, 'dragend', function (event) {
			    $('#sec_latitud').val(this.getPosition().lat());
				$('#sec_longitud').val(this.getPosition().lng());
			});
		 
		}
	
	function totalMarkers(){
		  return markers.length;
	}

	// Sets the map on all markers in the array.
	function setAllMap(map) {
	  for (var i = 0; i < markers.length; i++) {
	    markers[i].setMap(map);
	  }
	}

	// Removes the markers from the map, but keeps them in the array.
	function clearMarkers() {
	  setAllMap(null);
	}

	// Deletes all markers in the array by removing references to them.
	function deleteMarkers() {
	  clearMarkers();
	  markers = [];
	}

	function codeAddress(zoom) {

		map.setZoom(zoom);
		
		  var address = document.getElementById('address').value;
		  geocoder.geocode( { 'address': address}, function(results, status) {
		    if (status == google.maps.GeocoderStatus.OK) {
		    	map.setCenter(results[0].geometry.location);
		      /* var marker = new google.maps.Marker({
		          map: map,
		          position: results[0].geometry.location
		      }); */
		    } else {
		      //alert('Geocode was not successful for the following reason: ' + status);
		    }
		  });
	}

	function codeLatLng() {
		  //var input = document.getElementById('latlng').value;
		  //var latlngStr = input.split(',', 2);
		  var lat = parseFloat($('#sec_latitud').val());
		  var lng = parseFloat($('#sec_longitud').val());
		  var latlng = new google.maps.LatLng(lat, lng);
		  geocoder.geocode({'latLng': latlng}, function(results, status) {
		    if (status == google.maps.GeocoderStatus.OK) {
		      if (results[1]) {
		    	map.setCenter(results[1].geometry.location);
		        map.setZoom(17);
		        marker = new google.maps.Marker({
		            position: latlng,
		            map: map
		        });
		        infowindow.setContent(results[1].formatted_address);
		        infowindow.open(map, marker);
		      } else {
		        alert('No results found');
		      }
		    } else {
		      alert('Geocoder failed due to: ' + status);
		    }
		  });
		}
	
	google.maps.event.addDomListener(window, 'load', initialize);
</script>
