<div class="titulo-ventana"><i class="fa fa-gears fa-fw"></i> Par&aacute;metros - Listado de Sectores</div>
<hr class="hr-style" /> 
    
 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'sector', 'action'=>'ingresar'));?>" class="btn btn-primary">
     	<i class="fa fa-plus-circle"></i> Nuevo</a>
 	 </th>
 	 <th>Ciudad</th>
     <th>Nombre</th>
     <th>Latitud</th>
     <th>Longitud</th>
     <th>Ubicaci&oacute;n</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->sector as $sector) : ?>
 <tr>
 	 <td width="7%" style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'editar', 'id' => $sector->getSec_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'eliminar', 'id' => $sector->getSec_id()))?>" onclick="return eliminarRegistro('<?php echo $sector->getSec_nombre() ?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
     <td><?php echo $this->escapeHtml($sector->getCiu_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($sector->getSec_nombre());?></td>
     <td><?php echo $this->escapeHtml($sector->getSec_latitud());?></td>
     <td><?php echo $this->escapeHtml($sector->getSec_longitud());?></td>
     <td><?php echo $this->escapeHtml($sector->getSec_ubicacion());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
