 <?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Sectores</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead style="">
                 <tr>
                 	 <th>
                 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'sector', 'action'=>'ingresar'));?>" class="btn btn-primary">
                     	<i class="fa fa-plus-circle"></i> Nuevo</a>
                 	 </th>
                 	 <th>Ciudad</th>
                     <th>Nombre</th>
                     <th class="hidden-xs">Latitud</th>
                     <th class="hidden-xs">Longitud</th>
                     <th class="hidden-xs">Ubicaci&oacute;n</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                 foreach ($this->sector as $sector) : ?>
                 <tr>
                 	 <td class="dataTableIcons">
                 	 	<a class="fa-lg" href="<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'editar', 'id' => $sector->getSec_id()))?>"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp;
                 	 	<a class="fa-lg" href="<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'eliminar', 'id' => $sector->getSec_id()))?>" onclick="return eliminarRegistro('<?php echo $sector->getSec_nombre() ?>');"><i class="fa fa-trash-o"></i></a>
                 	 </td>
                     <td><?php echo $this->escapeHtml($sector->getCiu_nombre_es());?></td>
                     <td><?php echo $this->escapeHtml($sector->getSec_nombre());?></td>
                     <td class="hidden-xs"><?php echo $this->escapeHtml($sector->getSec_latitud());?></td>
                     <td class="hidden-xs"><?php echo $this->escapeHtml($sector->getSec_longitud());?></td>
                     <td class="hidden-xs"><?php echo $this->escapeHtml($sector->getSec_ubicacion());?></td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>