<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); 

//FORMULARIO
$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'usuarios', array (
		'controller' => 'usuarios',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' )
->setAttribute ('class', 'form-horizontal');
$formLabel = $this->plugin ( 'formLabel' );

$usu_id = $form->get ( 'usu_id' );
$ciu_id= $form->get ( 'ciu_id' );
$usu_usuario = $form->get ( 'usu_usuario' );
$usu_email = $form->get ( 'usu_email' );
$usu_nombre = $form->get ( 'usu_nombre' );
$usu_apellido = $form->get ( 'usu_apellido' );
$usu_clave = $form->get ( 'usu_clave' );
$usu_clave_check = $form->get ( 'usu_clave_check' );
$usu_estado = $form->get ( 'usu_estado' );

//EMPIEZA A ESCRIBIRSE EL FORMULARIO
echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $usu_id );
echo $this->formelementerrors ( $usu_id );

?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span><?php echo $this->titulo ?> usuario</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Ingrese la informaci&oacute;n solicitada. Todos los campos con * son obligatorios.</label>
        			</div>
    			</div>
    			<div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1">
                        <?php  
                		echo $formLabel->openTag() . $ciu_id->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-md-8">
            			<?php 
            			echo html_entity_decode( $this->formselect ( $ciu_id ) );
					    echo html_entity_decode( $this->formelementerrors ( $ciu_id ) ); 
            			?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $usu_nombre->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-md-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $usu_nombre ) );
					    echo html_entity_decode( $this->formelementerrors ( $usu_nombre ) );  
            			?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $usu_apellido->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-md-8">
                		<?php 
                		echo html_entity_decode( $this->formtext ( $usu_apellido ) );
					    echo html_entity_decode( $this->formelementerrors ( $usu_apellido ) );  
                		?>
                	</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1">
                        <?php 
                        echo $formLabel->openTag() . $usu_email->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-md-8">
                	   <?php 
                		echo html_entity_decode( $this->formtext ( $usu_email ) );
                		echo html_entity_decode( $this->formelementerrors ( $usu_email ) );
                		?>
                	</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1">
                        <?php 
                        echo $formLabel->openTag() . $usu_estado->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-md-8">
                		<?php 
                		echo html_entity_decode( $this->formselect ( $usu_estado ) );
                		echo html_entity_decode( $this->formelementerrors ( $usu_estado ) );
                		?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1">
                        <?php 
                        echo $formLabel->openTag() . $usu_usuario->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-md-8">
                		<?php 
                		echo html_entity_decode( $this->formtext ( $usu_usuario ) );
					    echo html_entity_decode( $this->formelementerrors ( $usu_usuario ) ); 
                		?>
            		</div>
                </div>
                
                <?php if($this->edit !== true) :?>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1">
                        <?php 
                        echo $formLabel->openTag() . $usu_clave->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-md-8">
                		<?php 
                		echo html_entity_decode( $this->formpassword ( $usu_clave ) );
					    echo html_entity_decode( $this->formelementerrors ( $usu_clave ) ); 
                		?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1">
                        <?php 
                        echo $formLabel->openTag() . $usu_clave_check->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-md-8">
                	   <?php 
                		echo html_entity_decode( $this->formpassword ( $usu_clave_check ) );
					    echo html_entity_decode( $this->formelementerrors ( $usu_clave_check ) ); 
                		?>
            		</div>
                </div>
                <?php endif;?>
                <div class="row">
    				<div class="form-group col-md-12">
            		     <div align="center">
            				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				            <a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'index'))?>" class ="btn btn-primary">Cancelar</a>
            			</div>	
        			</div>
    			</div>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>