 <?php
 // module/Empresas/view/empresas/empresas/add.phtml:

 $title = 'Asociar Usuario';
 $this->headTitle($title);

 ?>
<div class="row">
	<div class="col-md-12">
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td width="50" valign="middle"><img src="<?php echo $this->basepath() . '/img/png/usuarios_grande.png'?>" border="0" /></td>
		<td class="titulo_menu_item_pages"><span class="titulo_modulo_pages"><?php echo $this->escapeHtml($title); ?></span><br />Registre toda la información solicitada para ingresar un nuevo usuario.</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-bottom: 20px;"><hr /></td>
	</tr>
</table>
</div>
</div>

<?php
$form = $this->formulario;
$detalles = $this->detalles;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'usuarios', array (
		'controller' => 'usuarios',
		'action' => 'validarRolUsuario' 
) ) );

$form->setAttribute ( 'method', 'post' );

$formLabel = $this->plugin ( 'formLabel' );

echo $this->form ()->openTag ( $form );

echo $this->formRow($form->get('usu_id'));
?>

<ul class="error_container bs-callout bs-callout-danger">

</ul>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-txt">&nbsp;</div>
	<div class="col-md-12"><h3 align="left">Informaci&oacute;n General</h3><hr/></div>
	<div class="row azul-form-row">
		<div class="col-md-6"><?php echo $this->formRow($form->get('usu_nombre')); ?></div>
		<div class="col-md-6"><?php echo $this->formRow($form->get('rol_id')); ?></div>
	</div>
</div>
<div align="center">
	<?php echo $this->formRow($form->get('ingresar')); ?>
&nbsp;
<a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'index'))?>" class ="btn btn-primary">Cancelar</a>
</div>
<?php echo $this->form()->closeTag(); ?>

<script type="text/javascript">
/*
	$(document).ready(function(){
		//Inicio Bloque Validador JS
		$("#usuarios").validate({
			errorLabelContainer: $("ul.error_container"),
			wrapper: 'li',
			rules: {
				US_CODIGO: {required:true},
				ROL_ID: {required:true}
	 		},
	 		messages:{
				US_CODIGO: 	{required:'Usuario es un campo requerido'},
				ROL_ID: 	{required:'Rol es un campo requerido'}
	 	 	}
		});
	});
	*/
</script>