 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td>
			<div width="50" valign="middle" class="icon-content"><img src="<?php echo $this->basepath() . '/img/png/usuarios_grande.png'?>" border="0" /></div>
			<div class="txt-icon-content">Ingresar un nuevo usuario<br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo usuario.</div>
			<div><br /><hr /></div>
		</td>
	</tr>
</table>
 <div style="padding-bottom: 30px;">
     <a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action'=>'add'));?>" class="btn btn-primary">
     <img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar un nuevo registro</a>
 </div>
<div style=" padding-bottom: 100px;  ">
 <table class="table table-striped table-bordered table-hover" style="font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>&nbsp;</th>
     <th>Ciudad</th>
     <th>Nombre</th>
     <th>Apellido</th>
     <th>Usuario</th>
     <th>Clave</th>
     <th>Email</th>
     <th>Estado</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->usuarios as $usuario) : ?>
 <tr>
 	 <td width="150">
 	 	<a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'edit', 'id' => $usuario->getUsu_id()))?>" title="Actualizar" alt="Actualizar">Editar</a> |
 	 	<a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'asociar', 'id' => $usuario->getUsu_id()))?>" title="Asociar Permisos" alt="Asociar Permisos">Asociar Permisos</a> |
 	 	<a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'eliminar', 'id' => $usuario->getUsu_id()))?>" title="Eliminar" alt="Eliminar">Eliminar</a>
 	 </td>
     <td><?php echo $this->escapeHtml($usuario->getCiu_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_nombre());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_apellido());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_usuario());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_clave());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_email());?></td>
     <td><?php echo (strtoupper($usuario->getUsu_estado()) == 'A') ?  'Activo' :  'Inactivo';?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>