<div class="titulo-ventana"><i class="fa fa-users fa-fw"></i> Administraci&oacute;n - Listado de Usuarios</div>
<hr class="hr-style" />

 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th width="10%">
 	 	<a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action'=>'add'));?>" class="btn btn-primary">
     	<i class="fa fa-plus-circle"></i> Nuevo</a>
 	 </th>
     <th>Ciudad</th>
     <th>Nombre</th>
     <th>Apellido</th>
     <th>Usuario</th>
     <th>Clave</th>
     <th>Email</th>
     <th>Estado</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->usuarios as $usuario) : ?>
 <tr>
 	 <td style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'edit', 'id' => $usuario->getUsu_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-success" href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'asociar', 'id' => $usuario->getUsu_id()))?>"><i class="fa fa-list"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'eliminar', 'id' => $usuario->getUsu_id()))?>" onclick="return eliminarRegistro('<?php echo $usuario->getUsu_nombre() . ' ' . $usuario->getUsu_apellido()?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
     <td><?php echo $this->escapeHtml($usuario->getCiu_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_nombre());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_apellido());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_usuario());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_clave());?></td>
     <td><?php echo $this->escapeHtml($usuario->getUsu_email());?></td>
     <td><?php echo (strtoupper($usuario->getUsu_estado()) == 'A') ?  'Activo' :  'Inactivo';?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>