<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Usuarios</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                 	 <th width="10%">
                 	 	<a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action'=>'add'));?>" class="btn btn-primary">
                     	<i class="fa fa-plus-circle"></i> Nuevo</a>
                 	 </th>
                     <th class="hidden-xs">Ciudad</th>
                     <th>Nombre</th>
                     <th>Apellido</th>
                     <th class="hidden-xs">Usuario</th>
                     <th class="hidden-xs">Clave</th>
                     <th class="hidden-xs">Email</th>
                     <th class="hidden-xs">Estado</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                 foreach ($this->usuarios as $usuario) : ?>
                 <tr>
                 	 <td class="dataTableIcons">
                 	 	<a class="fa-lg" href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'edit', 'id' => $usuario->getUsu_id()))?>"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp;
                 	 	<a class="fa-lg" href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'asociar', 'id' => $usuario->getUsu_id()))?>"><i class="fa fa-list"></i></a>&nbsp;&nbsp;&nbsp;
                 	 	<a class="fa-lg" href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'eliminar', 'id' => $usuario->getUsu_id()))?>" onclick="return eliminarRegistro('<?php echo $usuario->getUsu_nombre() . ' ' . $usuario->getUsu_apellido()?>');"><i class="fa fa-trash-o"></i></a>
                 	 </td>
                     <td class="hidden-xs"><?php echo $this->escapeHtml($usuario->getCiu_nombre_es());?></td>
                     <td><?php echo $this->escapeHtml($usuario->getUsu_nombre());?></td>
                     <td><?php echo $this->escapeHtml($usuario->getUsu_apellido());?></td>
                     <td class="hidden-xs"><?php echo $this->escapeHtml($usuario->getUsu_usuario());?></td>
                     <td class="hidden-xs"><?php echo $this->escapeHtml($usuario->getUsu_clave());?></td>
                     <td class="hidden-xs"><?php echo $this->escapeHtml($usuario->getUsu_email());?></td>
                     <td class="hidden-xs"><?php echo (strtoupper($usuario->getUsu_estado()) == 'A') ?  'Activo' :  'Inactivo';?></td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>