<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Ciudades</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                     <table class="table table-striped table-hover" style="font-size: 12px;" >
                     <thead>
                     <tr>
                     	 <th>
                     	 	<a href="<?php echo $this->url('parametros', array('controller' => 'ciudad', 'action'=>'ingresar'));?>" class="btn btn-primary">
                         	<i class="fa fa-plus-circle"></i> Nuevo</a>
                         </th>
                     	 <th>Estado</th>
                         <th>Nombre <span class="hidden-xs">Espa&ntilde;ol</span></th>
                         <th class="hidden-xs">Nombre Ingl&eacute;s</th>
                         <th class="hidden-xs">C&oacute;digode Tel&eacute;fono</th>
                     </tr>
                     </thead>
                     <tbody>
                     <?php 
                     foreach ($this->ciudad as $vehiculos) : ?>
                     <tr>
                     	 <td class="dataTableIcons">
                     	 	<a class="fa-lg" href="<?php echo $this->url('parametros', array('controller' => 'ciudad', 'action' => 'editar', 'id' => $vehiculos->getCiu_id()))?>"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp;
                     	 	<a class="fa-lg" href="<?php echo $this->url('parametros', array('controller' => 'ciudad', 'action' => 'eliminar', 'id' => $vehiculos->getCiu_id()))?>" onclick="return eliminarRegistro('<?php echo $vehiculos->getCiu_nombre_es()?>');"><i class="fa fa-trash-o"></i></a>
                     	 </td>
                         <td><?php echo $this->escapeHtml($vehiculos->getEst_nombre_es());?></td>
                         <td><?php echo $this->escapeHtml($vehiculos->getCiu_nombre_es());?></td>
                         <td class="hidden-xs"><?php echo $this->escapeHtml($vehiculos->getCiu_nombre_en());?></td>
                         <td class="hidden-xs"><?php echo $this->escapeHtml($vehiculos->getCiu_codigo_telefono());?></td>
                     </tr>
                     <?php endforeach; ?>
                     </tbody>
                     </table>
			</div>
        </div>
    </div>
</div>