<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Men&uacute; de Opciones</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                 	 <th width="7%">
                 	 	<a href="<?php echo $this->url('usuarios', array('controller' => 'menu', 'action'=>'ingresar'));?>" class="btn btn-primary">
                     	<i class="fa fa-plus-circle"></i> Nuevo</a>
                 	 </th>
                	 <th>N&uacute;mero</th>
                     <th>Nombre</th>
                     <th>Etiqueta</th>
                     <th>Aplicaci&oacute;n</th>
                     <th>&Iacute;cono</th>
                     <th>Padre</th>
                     <th>&iquest;Aplica Divisor?</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                 foreach ($this->menu as $menu) : ?>
                 <tr>
                 	 <td class="dataTableIcons">
                 	 	<a class="fa-lg" href="<?php echo $this->url('usuarios', array('controller' => 'menu', 'action' => 'editar', 'id' => $menu->getMen_id()))?>"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp;
                 	 	<a class="fa-lg" href="<?php echo $this->url('usuarios', array('controller' => 'menu', 'action' => 'eliminar', 'id' => $menu->getMen_id()))?>" onclick="return eliminarRegistro('<?php echo $menu->getMen_nombre()?>');"><i class="fa fa-trash-o"></i></a>
                 	 </td>
                 	 <td><?php echo $this->escapeHtml($menu->getMen_id());?></td>
                     <td><?php echo $this->escapeHtml($menu->getMen_nombre());?></td>
                     <td><?php echo $this->escapeHtml($menu->getMen_etiqueta());?></td>
                     <td><?php echo $this->escapeHtml($menu->getApl_nombre());?></td>
                     <td><?php echo $menu->getMen_icon();?></td>
                     <td><?php echo $this->escapeHtml($menu->getMen_padre());?></td>
                     <td>
                     	<?php 
                     		echo  $this->escapeHtml($menu->getMen_divisor()) == 'S'? 'SI' : 'NO'; 
                     	?>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>