<?php

$form = $this->formulario;
$detalles = $this->detalles;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'usuarios', array (
		'controller' => 'menu',
		'action' => 'validar' 
) ) );

$formLabel = $this->plugin ( 'formLabel' );

$men_id = $form->get('men_id');
$men_nombre = $form->get('men_nombre');
$men_etiqueta = $form->get('men_etiqueta');
$apl_id = $form->get('apl_id');
$men_icon = $form->get('men_icon');
$men_padre = $form->get('men_padre');
$men_divisor = $form->get('men_divisor');

echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $men_id );
echo $this->formelementerrors ( $men_id );
?>

<ul class="error_container bs-callout bs-callout-danger">

</ul>

<div class="panel panel-default">
	<div class="panel-heading panel-heading-txt">&nbsp;</div>
	
	<table width="100%" cellpadding="5">
			<tr>
				<td>
					<br />
					<div width="50" valign="middle" class="icon-content"><img src="<?php echo $this->basepath() . '/img/png/usuarios_grande.png'?>" border="0" /></div>
					<div class="txt-icon-content">Ingresar un nuevo men&uacute;<br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo men&uacute;.</div>
					<div><br /></div>
				</td>
			</tr>
			<tr>
				<td>
				<?php echo $formLabel->openTag() . $men_nombre->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $men_nombre ) );
					  echo html_entity_decode( $this->formelementerrors ( $men_nombre ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $men_etiqueta->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $men_etiqueta ) );
					  echo html_entity_decode( $this->formelementerrors ( $men_etiqueta ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $apl_id->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formselect ( $apl_id ) );
					  echo html_entity_decode( $this->formelementerrors ( $apl_id ) ); 
				?>
				</td>
			</tr>
			<tr>
				<td>
				<?php echo $formLabel->openTag() . $men_icon->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $men_icon ) );
					  echo html_entity_decode( $this->formelementerrors ( $men_icon ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $men_padre->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $men_padre ) );
					  echo html_entity_decode( $this->formelementerrors ( $men_padre ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $men_divisor->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formselect ( $men_divisor ) );
					  echo html_entity_decode( $this->formelementerrors ( $men_divisor ) ); 
				?>
				</td>
			</tr>
		</table>
	
</div>

<div align="center">
	<?php echo $this->formRow($form->get('ingresar')); ?>&nbsp;
	<a href="<?php echo $this->url('usuarios', array('controller' => 'menu', 'action' => 'index'))?>" class ="btn btn-primary">Cancelar</a>
</div>

<?php echo $this->form()->closeTag(); ?>