 <?php $this->headTitle('Listado de Veh&iacute;culos'); ?>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td>
			<div width="50" valign="middle" class="icon-content"><img src="<?php echo $this->basepath() . '/img/png/ciudad_grande.png'?>" border="0" /></div>
			<div class="txt-icon-content">Ingresar un nuevo veh&iacute;culo<br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo veh&iacute;culo.</div>
			<div><br /><hr /></div>
		</td>
	</tr>
</table>
<div style=" padding-bottom: 100px;  ">

<?php foreach ($this->camara as $camara) : ?>
 <table>
 	<tr>
 		<td><a href="<?php echo $this->url('vehiculo', array('controller' => 'vehiculo', 'action'=>'camara', 'id' => $camara->getVeh_id()));?>"><img src="<?php echo $this->basepath() . '/img/png/camara.png'?>" border="0" /></a></td>
 	</tr>
 </table>
 <?php endforeach;?>

<br /><br />
 <div style="padding-bottom: 30px;">
     <a href="<?php echo $this->url('vehiculo', array('controller' => 'vehiculo', 'action'=>'ingresar'));?>" class="btn btn-primary">
     <img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar un nuevo registro</a>
 </div>
 <table class="table table-striped table-bordered table-hover" style="font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>&nbsp;</th>
 	 <th>Tipo Vehiculo</th>
     <th>Marca</th>
     <th>Modelo</th>
     <th>Placa</th>
     <th>C&aacute;mara Activa</th>
 </tr>
 </thead>
 <tbody>
 <?php foreach ($this->vehiculos as $vehiculos) : ?>
 <tr>
 	 <td width="150">
 	 	<a href="<?php echo $this->url('vehiculo', array('controller' => 'vehiculo', 'action' => 'editar', 'id' => $vehiculos->getVeh_id()))?>" title="Actualizar" alt="Actualizar">Editar</a> |
 	 	<a href="<?php echo $this->url('vehiculo', array('controller' => 'vehiculo', 'action' => 'eliminar', 'id' => $vehiculos->getVeh_id()))?>" title="Eliminar" alt="Eliminar">Eliminar</a>
 	 </td>
     <td><?php echo $this->escapeHtml($vehiculos->getTip_veh_descripcion());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getVeh_marca());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getVeh_modelo());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getVeh_placa());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getVeh_camara_activa());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>