<div class="titulo-ventana"><i class="fa fa-car fa-fw"></i> Veh&iacute;culo - Listado de Veh&iacute;culos</div>
<hr class="hr-style" />
<div>
<?php foreach ($this->camara as $camara) : ?>
 <table>
 	<tr>
 		<td><a href="<?php echo $this->url('vehiculo', array('controller' => 'vehiculo', 'action'=>'camara', 'id' => $camara->getVeh_id()));?>"><img src="<?php echo $this->basepath() . '/img/png/camara.png'?>" border="0" class="img-rounded" /></a></td>
 	</tr>
 </table>
 <?php endforeach;?>
</div>
<br />
  <hr class="hr-style" />   
 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th width="7%">
 	 	<a href="<?php echo $this->url('vehiculo', array('controller' => 'vehiculo', 'action'=>'ingresar'));?>" class="btn btn-primary">
     	<i class="fa fa-plus-circle"></i> Nuevo</a>
 	 </th>
 	 <th>Tipo Veh&iacute;culo</th>
     <th>Marca</th>
     <th>Modelo</th>
     <th>Placa</th>
     <th>C&aacute;mara Activa</th>
 </tr>
 </thead>
 <tbody>
 <?php foreach ($this->vehiculos as $vehiculos) : ?>
 <tr>
 	 <td style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('vehiculo', array('controller' => 'vehiculo', 'action' => 'editar', 'id' => $vehiculos->getVeh_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('vehiculo', array('controller' => 'vehiculo', 'action' => 'eliminar', 'id' => $vehiculos->getVeh_id()))?>" onclick="return eliminarRegistro('<?php echo $vehiculos->getTip_veh_descripcion() ?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
     <td><?php echo $this->escapeHtml($vehiculos->getTip_veh_descripcion());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getVeh_marca());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getVeh_modelo());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getVeh_placa());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getVeh_camara_activa());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>