<?php $this->headTitle('Listado de Aplicaciones'); ?>
<div style=" padding-bottom: 100px;  ">
 <table class="table table-striped table-bordered table-hover" style="font-size: 12px;" >
 <thead style="">
 <tr>
     <th>Nombre</th>
     <th>Descripci&oacute;n</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->aplicaciones as $aplicacion) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($aplicacion->getApl_nombre());?></td>
     <td><?php echo $this->escapeHtml($aplicacion->getApl_descripcion());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>