<div class="titulo-ventana"><i class="fa fa-users fa-fw"></i> Administraci&oacute;n - Listado de Aplicaciones</div>
<hr class="hr-style" />

 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
     <th>Nombre</th>
     <th>Descripci&oacute;n</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->aplicaciones as $aplicacion) : ?>
 <tr style=" height: 35px;">
     <td><?php echo $this->escapeHtml($aplicacion->getApl_nombre());?></td>
     <td><?php echo $this->escapeHtml($aplicacion->getApl_descripcion());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
