<div class="titulo-ventana"><i class="fa fa-gears fa-fw"></i> Clientes - Listado de Clientes</div>
<hr class="hr-style" />

 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th>&nbsp;</th>
 	 <th>Estado</th>
     <th>Nombre Espa&ntilde;ol</th>
     <th>Nombre Ingl&eacute;s</th>
     <th>C&oacute;digo de Tel&eacute;fono</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->ciudad as $vehiculos) : ?>
 <tr>
 	 <td width="7%" style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('parametros', array('controller' => 'ciudad', 'action' => 'editar', 'id' => $vehiculos->getCiu_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('parametros', array('controller' => 'ciudad', 'action' => 'eliminar', 'id' => $vehiculos->getCiu_id()))?>" onclick="return eliminarRegistro('<?php echo $vehiculos->getCiu_nombre_es()?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
     <td><?php echo $this->escapeHtml($vehiculos->getEst_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getCiu_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getCiu_nombre_en());?></td>
     <td><?php echo $this->escapeHtml($vehiculos->getCiu_codigo_telefono());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>