<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Clientes</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                 	 <th>&nbsp;</th>
                 	 <th>Nombre</th>
                 	 <th>Apellido</th>
                     <th>Email</th>
                     <th>Saldo</th>
                     <th>Estado</th>
                     <th>Fecha Registro</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                 $suma = 0;
                 foreach ($this->cliente as $transaccion) : ?>
                 <tr>
                     <td class="dataTableIcons">
                 	 	<a class="fa-lg" href="<?php echo $this->url('clientes', array('controller' => 'perfil', 'action' => 'perfil', 'id' => $transaccion->getCli_id())) ?>"><i class="fa fa-user"></i></a>&nbsp;
                 	 </td>
                     <td><?php echo $this->escapeHtml($transaccion->getUsu_nombre());?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getUsu_apellido());?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getUsu_email());?></td>
                     <td><?php echo '$ ' . $this->escapeHtml($transaccion->getCli_saldo());?></td>
                     <td><?php echo $transaccion->getUsu_estado() == 'A' ? 'Activo' : 'Inactivo'; ?></td>
                     <td><?php echo $this->escapeHtml($transaccion->getUsu_fecha_registro());?></td>
                 </tr>
                 
                 <?php $suma += $transaccion->getCli_saldo(); ?>
                 
                 <?php endforeach; ?>
                 <tr>
                    <td style="height: 28px;">&nbsp;</td>
                    <td style="border-left: 1px solid #ffffff;">&nbsp;</td>
                    <td style="border-left: 1px solid #ffffff;">&nbsp;</td>
                    <td style="border-left: 1px solid #ffffff;">&nbsp;</td>
                    <td class="success" style="font-size: 14px; border: 0px solid #ffffff;"><b>Saldo Total: </b></td>
                    <td class="success" style="font-size: 14px; border: 0px solid #ffffff;"><b><?php echo '$ ' . $suma;?></b></td>
                    <td style="border-left: 1px solid #ffffff;">&nbsp;</td>
                    <td style="border-left: 1px solid #ffffff;">&nbsp;</td>
                 </tr>
                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>