<div class="titulo-ventana">Monitoreo - Buscar</div>
<hr style="margin-bottom: 20px; margin-top: 0px;" />

<?php
$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'monitoreo', array (
		'controller' => 'control',
		'action' => 'control' 
) ) )->setAttribute ( 'method', 'post' );
$formLabel = $this->plugin ( 'formLabel' );

$ciu_id = $form->get ( 'ciu_id' );
$pai_id = $form->get ( 'pai_id' );
$est_id = $form->get ( 'est_id' );

//$date = new Fecha();
echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $form->get ( 'pai_id_hidden' ) );
echo $this->formhidden ( $form->get ( 'est_id_hidden' ) );
echo $this->formhidden ( $form->get ( 'ciu_id_hidden' ) );

?>
<table width="100%" cellpadding="5">
	<tr>
		<td>
			<?php echo $formLabel->openTag() . $pai_id->getLabel() . $formLabel->closeTag();
			      echo html_entity_decode( $this->formselect ( $pai_id ) );
				  echo html_entity_decode( $this->formelementerrors ( $pai_id ) ); 
			?>
		</td>
		<td>
			<?php echo $formLabel->openTag() . $est_id->getLabel() . $formLabel->closeTag();
			      echo html_entity_decode( $this->formselect ( $est_id ) );
				  echo html_entity_decode( $this->formelementerrors ( $est_id ) ); 
			?>
		</td>
		<td>
			<?php echo $formLabel->openTag() . $ciu_id->getLabel() . $formLabel->closeTag();
			      echo html_entity_decode( $this->formselect ( $ciu_id ) );
				  echo html_entity_decode( $this->formelementerrors ( $ciu_id ) ); 
			?>
		</td>
		<td valign="bottom">
			<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
		</td>
	</tr>
</table>
<?php echo $this->form()->closeTag(); ?>
<br />
<hr />
<br />
 <script>
//FUNCION PARA CARGAR EL COMBO BOX DE ESTADOS EN BASE A UN PAIS SELECCIONADO
 $("#pai_id").change(function() {
 	if($('#pai_id').val() != '' && $('#pai_id').val() != null){
         $.ajax({
             url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'sucursalesAjax')) ?>",
             type: "POST",
             dataType: "json",
             data: "pais=" + $('#pai_id').val(),
             beforeSend: function() {
             	$("#est_id").html("");
             	$("#est_id").append('<option>Procesando, espere por favor...</option>');
             }
         }).done(function(estados) {
             $("#est_id").html("");
             $("#est_id").append('<option value = "null">-- Seleccione un estado --</option>');
             for (estado in estados) {
                 $("#est_id").append('<option value="' + estado + '">' + estados[estado] + '</option>');
             }
             $("#est_id").prop("disabled", false);
             
         });

 	}else{
 		$("#est_id").prop("disabled", true);
 	}
 });

 //FUNCION PARA CARGAR EL COMBO BOX DE CIUDADES EN BASE A UN ESTADO
 $("#est_id").change(function() {
 	if($('#est_id').val() != '' && $('#est_id').val() != null){
         $.ajax({
         	url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'ciudadesAjax')) ?>",
             type: "POST",
             dataType: "json",
             data: "estado=" + $('#est_id').val(),
             beforeSend: function() {
             	$("#ciu_id").html("");
             	$("#ciu_id").append('<option>Procesando, espere por favor...</option>');
             }
         }).done(function(ciudades) {
             $("#ciu_id").html("");
             $("#ciu_id").append('<option value = "null">-- Seleccione una ciudad --</option>');
             for (ciudad in ciudades) {
                 $("#ciu_id").append('<option value="' + ciudad + '">' + ciudades[ciudad] + '</option>');
             }
             $("#ciu_id").prop("disabled", false);
         });
 	}else{
 		$("#ciu_id").prop("disabled", true);
 	}
 });

 //FUNCION PARA CARGAR LOS ESTADOS CUANDO EL FORMULARIO SEA DE ACTUALIZACION
 $("#pai_id").ready(function() {
 	if($('#pai_id').val() != '' && $('#pai_id').val() != null){
         $.ajax({
             url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'sucursalesAjax')) ?>",
             type: "POST",
             dataType: "json",
             data: "pais=" + $('#pai_id_hidden').val(),
             beforeSend: function() {
             	$("#est_id").html("");
             	$("#est_id").append('<option>Procesando, espere por favor...</option>');
             }
         }).done(function(estados) {
             $("#est_id").html("");
             $("#est_id").append('<option value = "null">-- Seleccione un estado --</option>');
             for (estado in estados) {
             	var selected = '';
 				if($("#est_id_hidden").val() == estado){
 					selected = 'selected="selected"';
 				}else{
 					selected = '';
 				}
                 
                 $("#est_id").append('<option value="' + estado + '" ' + selected + '>' + estados[estado] + '</option>');
             }
             $("#est_id").prop("disabled", false);

             $("#est_id").ready(function() {
             	if($('#est_id').val() != '' && $('#est_id').val() != null){
                     $.ajax({
                     	url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'ciudadesAjax')) ?>",
                         type: "POST",
                         dataType: "json",
                         data: "estado=" + $('#est_id_hidden').val(),
                         beforeSend: function() {
                         	$("#ciu_id").html("");
                         	$("#ciu_id").append('<option>Procesando, espere por favor...</option>');
                         }
                     }).done(function(ciudades) {
                         $("#ciu_id").html("");
                         $("#ciu_id").append('<option value = "null">-- Seleccione una ciudad --</option>');
                         for (ciudad in ciudades) {
                         	var selected = '';
                         	if($("#est_id_hidden").val() == ciudad){
             					selected = 'selected="selected"';
             				}else{
             					selected = '';
             				}
             				
                             $("#ciu_id").append('<option value="' + ciudad + '" '+selected+'>' + ciudades[ciudad] + '</option>');
                         }
                         $("#ciu_id").prop("disabled", false);

                     });
             	}else{
             		$("#ciu_id").prop("disabled", true);
             	}
             });

         });
 	}else{
 		$("#est_id").prop("disabled", true);
 	}
 });
 </script>