<strong>Module:</strong>        ZendSkeletonModule &raquo;
<strong>Controller:</strong>    Skeleton &raquo;
<strong>Action:</strong>        index

<fieldset class="gllpLatlonPicker" id="custom_id">
		<input type="text" class="gllpSearchField"> <input type="button"
			class="gllpSearchButton" value="Buscar">
		<div class="gllpMap">Google Maps</div>
		<?php
		//echo $this->formHidden ( $form->get ( 'par_latitude' ) );
		//echo $this->formHidden ( $form->get ( 'par_longitude' ) );
		?> 
 
		<input type="hidden" class="gllpZoom" value="1" />
		
		<input type="button" class="gllpUpdateButton" style="width:0px; height:0px; border:none; background:none;">
	</fieldset>