<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-md-6" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-globe fa-fw"></i>
					<span>Seleccionar ubicaci&oacute;n</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
                <?php
                	$form = $this->formulario;
                	$form->prepare ();
                	$form->setAttribute ( 'action', $this->url ( 'parqueaderos', array (
                			'controller' => 'parqueaderos',
                			'action' => 'validar' 
                	) ) )->setAttribute ( 'method', 'post' );
                
                	$formLabel = $this->plugin ( 'formLabel' );
                
                	$ciu_id = $form->get ( 'ciu_id' );
                	$pai_id = $form->get ( 'pai_id' );
                	$est_id = $form->get ( 'est_id' );
                
                	echo $this->form ()->openTag ( $form );
                ?>
                <?php 
                	echo $formLabel->openTag() . $pai_id->getLabel() . $formLabel->closeTag();
                  	echo html_entity_decode( $this->formselect ( $pai_id ) );
                  	echo html_entity_decode( $this->formelementerrors ( $pai_id ) ); 
                ?>
                <div><br /></div>
                <?php 
                	echo $formLabel->openTag() . $est_id->getLabel() . $formLabel->closeTag();
                  	echo html_entity_decode( $this->formselect ( $est_id ) );
                  	echo html_entity_decode( $this->formelementerrors ( $est_id ) ); 
                ?>
                <div><br /></div>
                <?php 
                	echo $formLabel->openTag() . $ciu_id->getLabel() . $formLabel->closeTag();
                  	echo html_entity_decode( $this->formselect ( $ciu_id ) );
                  	echo html_entity_decode( $this->formelementerrors ( $ciu_id ) ); 
                ?>
                <div><br /></div>
			</div>
        </div>
    </div>
    <div class="col-md-6" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-map-marker fa-fw"></i>
					<span>Parqueaderos disponibles</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
                <div style="width:100%;" >
                	<div id="map-canvas" style="height:300px; width:100%; margin:0 auto;"></div>
                </div>
			</div>
        </div>
    </div>
     
</div>

<div class="row" id="resultadosParqueo" style="display: none;">
    <div class="col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Parqueaderos disponibles <span class="hidden-xs">por sector</span></span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
                <div style="clear:both" id="sectoresParqueaderos" class="row" >
                	
                </div>
           </div>
       </div>
   </div>
</div>
     


<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>

<script>
	var map;
	var markers = [];
	var geocoder;
	/* A esta cosa hay que pasarle al layout */
	
	function initialize() {

		geocoder = new google.maps.Geocoder();
	    var lugar = new google.maps.LatLng(-0.1865943, -78.4305382);
	    var mapOptions = { zoom: 4, center: lugar };
	    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
		
		/*var markers=<?php //echo $sectores; ?>;
	     for (i = 0; i < markers.length; i++) {
			var data = markers[i]
			var myLatlng = new google.maps.LatLng(data.lat, data.lng);
			var marker = new google.maps.Marker({
				position: myLatlng,
				map: map,
				title: data.title
			});
			(function(marker, data) {
				// Attaching a click event to the current marker
				google.maps.event.addListener(marker, "click", function(e) {
					window.location.href="<?php //echo $this->basepath(); ?>/parqueaderos/sector/index/"+data.id;
				});

				var infowindow = new google.maps.InfoWindow({
					content: 	'<div>'+
								data.description+'<br>'+
								'Ocupados: '+data.ocupados+'/'+data.total+'<br>'+
								'</div>'
				});

				google.maps.event.addListener(marker, "mouseover", function(e) {
					infowindow.open(map,marker);
				});
				google.maps.event.addListener(marker, "mouseout", function(e) {
					infowindow.close(map,marker);
				});

			})(marker, data);
		}*/

	}

	function codeAddress(zoom) {

		map.setZoom(zoom);
		
		  //var address = document.getElementById('address').value;
		  var address = "";
		  geocoder.geocode( { 'address': address}, function(results, status) {
		    if (status == google.maps.GeocoderStatus.OK) {
		    	map.setCenter(results[0].geometry.location);

		    } else {
		    }
		  });
	}	
	
	google.maps.event.addDomListener(window, 'load', initialize);


	$(document).ready(function(){
		//FUNCION PARA CARGAR EL COMBO BOX DE ESTADOS EN BASE A UN PAIS SELECCIONADO
		$("#pai_id").change(function() {
			if($('#pai_id').val() != '' && $('#pai_id').val() != null){
		        $.ajax({
		            url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'sucursalesAjax')) ?>",
		            type: "POST",
		            dataType: "json",
		            data: "pais=" + $('#pai_id').val(),
		            beforeSend: function() {
		            	$("#est_id").html("");
		            	$("#est_id").append('<option>Procesando, espere por favor...</option>');
		            }
		        }).done(function(estados) {
		            $("#est_id").html("");
		            $("#est_id").append('<option value = "null">-- Seleccione un estado --</option>');
		            for (estado in estados) {
		                $("#est_id").append('<option value="' + estado + '">' + estados[estado] + '</option>');
		            }
		            $("#est_id").prop("disabled", false);

		            var pais = $('#pai_id option:selected').text();

		            codeAddress(7);
		            
		        });

		        $.ajax({
		        	url: "<?php echo $this->url('parqueaderos', array('controller' => 'parqueaderos', 'action' => 'sectores')) ?>",
		            type: "POST",
		            dataType: "json",
		            data: "pai_id=" + $('#pai_id').val()
		        }).done(function(sectores) {
		        	$('#sectoresParqueaderos').html('');
				    for (var i = 0; i < markers.length; i++) {
				   	    markers[i].setMap(null);
				    }

		        	for(sector in sectores){ //foreach sectores
		        		

						var myLatlng = new google.maps.LatLng(sectores[sector].lat, sectores[sector].lng);
						var marker = new google.maps.Marker({
							position: myLatlng,
							map: map,
							title: sectores[sector].title
						});
						(function(marker, data) {
							google.maps.event.addListener(marker, "click", function(e) {
								window.location.href="<?php echo $this->basepath(); ?>/parqueaderos/sector/index/"+data.id;
							});

							var infowindow = new google.maps.InfoWindow({
								content: 	'<div>'+
											data.description+'<br>'+
											'Ocupados: '+data.ocupados+'/'+data.total+'<br>'+
											'</div>'
							});

							google.maps.event.addListener(marker, "mouseover", function(e) {
								infowindow.open(map,marker);
							});

							google.maps.event.addListener(marker, "mouseout", function(e) {
								infowindow.close(map,marker);
							});

						})(marker, sectores[sector]);

						markers.push(marker);

						$('#sectoresParqueaderos').append(
							'<div class="col-md-3 sector">'+
							'<div class="panel panel-primary">'+
								'<div class="panel-heading"><a href="<?php echo $this->basepath(); ?>/parqueaderos/sector/index/'+sectores[sector].id+'">'+sectores[sector].description+'</a></div>'+
								'<div class="panel-body">'+
									'Ocupados: '+sectores[sector].ocupados+'/'+sectores[sector].total+
								'</div>'+
							'</div>'+
							'</div>'

						);

		        	} //fin foreach sectores
		        });

			}else{
				$("#est_id").prop("disabled", true);
			}
		});

		//FUNCION PARA CARGAR EL COMBO BOX DE CIUDADES EN BASE A UN ESTADO
		$("#est_id").change(function() {
			if($('#est_id').val() != '' && $('#est_id').val() != null){
		        $.ajax({
		        	url: "<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'ciudadesAjax')) ?>",
		            type: "POST",
		            dataType: "json",
		            data: "estado=" + $('#est_id').val(),
		            beforeSend: function() {
		            	$("#ciu_id").html("");
		            	$("#ciu_id").append('<option>Procesando, espere por favor...</option>');
		            }
		        }).done(function(ciudades) {
		            $("#ciu_id").html("");
		            $("#ciu_id").append('<option value = "null">-- Seleccione una ciudad --</option>');
		            for (ciudad in ciudades) {
		                $("#ciu_id").append('<option value="' + ciudad + '">' + ciudades[ciudad] + '</option>');
		            }
		            $("#ciu_id").prop("disabled", false);

		            var pais = $('#pai_id option:selected').text();
		            var estado = $('#est_id option:selected').text();

		            codeAddress(9);
		        });


		        $.ajax({
		        	url: "<?php echo $this->url('parqueaderos', array('controller' => 'parqueaderos', 'action' => 'sectores')) ?>",
		            type: "POST",
		            dataType: "json",
		            data: "est_id=" + $('#est_id').val()
		        }).done(function(sectores) {
		        	$('#sectores').html('');
				    for (var i = 0; i < markers.length; i++) {
				   	    markers[i].setMap(null);
				    }

				    $('#resultadosParqueo').attr('style','display:true');

		        	for(sector in sectores){ //foreach sectores
		        		

						var myLatlng = new google.maps.LatLng(sectores[sector].lat, sectores[sector].lng);
						var marker = new google.maps.Marker({
							position: myLatlng,
							map: map,
							title: sectores[sector].title
						});
						(function(marker, data) {
							google.maps.event.addListener(marker, "click", function(e) {
								window.location.href="<?php echo $this->basepath(); ?>/parqueaderos/sector/index/"+data.id;
							});

							var infowindow = new google.maps.InfoWindow({
								content: 	'<div>'+
											data.description+'<br>'+
											'Ocupados: '+data.ocupados+'/'+data.total+'<br>'+
											'</div>'
							});

							google.maps.event.addListener(marker, "mouseover", function(e) {
								infowindow.open(map,marker);
							});

							google.maps.event.addListener(marker, "mouseout", function(e) {
								infowindow.close(map,marker);
							});

						})(marker, sectores[sector]);

						markers.push(marker);

						$('#sectores').append(
							'<div class="col-md-3 sector">'+
							'<div class="panel panel-primary">'+
								'<div class="panel-heading"><a href="<?php echo $this->basepath(); ?>/parqueaderos/sector/index/'+sectores[sector].id+'">'+sectores[sector].description+'</a></div>'+
								'<div class="panel-body">'+
									'Ocupados: '+sectores[sector].ocupados+'/'+sectores[sector].total+
								'</div>'+
							'</div>'+
							'</div>'

						);

		        	} //fin foreach sectores
		        });



			}else{
				$("#ciu_id").prop("disabled", true);
			}
		});

		//FUNCION PARA CARGAR EL COMBO BOX DE CIUDADES EN BASE A UN ESTADO		
		$("#ciu_id").change(function() {
			if($('#ciu_id').val() != '' && $('#ciu_id').val() != null){
		        
		        $.ajax({
		        	url: "<?php echo $this->url('parqueaderos', array('controller' => 'parqueaderos', 'action' => 'sectores')) ?>",
		            type: "POST",
		            dataType: "json",
		            data: "ciu_id=" + $('#ciu_id').val()
		        }).done(function(sectores) {
		        	$('#sectores').html('');
				    for (var i = 0; i < markers.length; i++) {
				   	    markers[i].setMap(null);
				    }

		        	for(sector in sectores){ //foreach sectores
		        		

						var myLatlng = new google.maps.LatLng(sectores[sector].lat, sectores[sector].lng);
						var marker = new google.maps.Marker({
							position: myLatlng,
							map: map,
							title: sectores[sector].title
						});
						(function(marker, data) {
							google.maps.event.addListener(marker, "click", function(e) {
								window.location.href="<?php echo $this->basepath(); ?>/parqueaderos/sector/index/"+data.id;
							});

							var infowindow = new google.maps.InfoWindow({
								content: 	'<div>'+
											data.description+'<br>'+
											'Ocupados: '+data.ocupados+'/'+data.total+'<br>'+
											'</div>'
							});

							google.maps.event.addListener(marker, "mouseover", function(e) {
								infowindow.open(map,marker);
							});

							google.maps.event.addListener(marker, "mouseout", function(e) {
								infowindow.close(map,marker);
							});

						})(marker, sectores[sector]);

						markers.push(marker);

						$('#sectores').append(
							'<div class="col-md-3 sector">'+
							'<div class="panel panel-primary">'+
								'<div class="panel-heading"><a href="<?php echo $this->basepath(); ?>/parqueaderos/sector/index/'+sectores[sector].id+'">'+sectores[sector].description+'</a></div>'+
								'<div class="panel-body">'+
									'Ocupados: '+sectores[sector].ocupados+'/'+sectores[sector].total+
								'</div>'+
							'</div>'+
							'</div>'

						);

		        	} //fin foreach sectores
		        });

		        codeAddress(13);

			};

		});

	});
</script>
