<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row" id="resultadosParqueo">
    <div class="col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Parqueaderos disponibles <span class="hidden-xs">por sector</span></span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">y
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
                <div style="clear:both" id="sectoresParqueaderos" class="row" >
                	
                </div>
           </div>
       </div>
   </div>
</div>
    