 <?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>
<?php 

    $form = $this->formulario;
    $form->prepare ();
    $form->setAttribute ( 'action', $this->url ( 'parqueaderos', array (
            'controller' => 'parqueaderos',
            'action' => 'tickets' 
    ) ) )->setAttribute ( 'method', 'post' )
    ->setAttribute ('class', 'form-horizontal');
    $formLabel = $this->plugin ( 'formLabel' );

    $nro_ticket  =   $form->get('nro_ticket');
    
 ?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Consulta de Tickets</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">

                
                <div class="row">
                    <?php echo $this->form ()->openTag ( $form ); ?>

                    <div class="control-label col-md-2 col-lg-2 ">
                        <?php  
                            echo $formLabel->openTag() . $nro_ticket->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <?php 
                        echo html_entity_decode( $this->formtext ( $nro_ticket ) );
                        echo html_entity_decode( $this->formelementerrors ( $nro_ticket ) );
                        ?>
                    </div>
                    <div class="control-label col-md-2 col-lg-2 ">
                        <?php echo $this->formsubmit( $form->get ( 'buscar' ) ) ?>
                    </div>

                    <?php echo $this->form()->closeTag(); ?>
                </div>


                <?php if(sizeof($this->tickets)>0): ?>
                    <table class="table table-striped table-hover" style="font-size: 12px;" >
                        <thead>
                        <tr>
                            <th>Nro. Ticket</th>
                            <th>Plaza</th>
                            <th>Placa</th>
                            <th>Hora Ticket</th>
                            <th>Tiempo (minutos)</th>
                        </tr>
                        </thead>
                        <tbody>
                            
                            <?php foreach($this->tickets as $ticket): ?>
                            <tr>
                            	<td><?php echo $ticket->getNro_ticket() ?></td>
                                <td><?php echo $ticket->getPar_id() ?></td>
                                <td><?php echo strtoupper($ticket->getAut_placa()) ?></td>
                                <td><?php echo $ticket->getLog_par_fecha_ingreso() ?></td>
                                <td><?php echo $ticket->getLog_par_horas_parqueo() ?></td>
                            </tr>
                            <?php endforeach; ?>
                               
                        </tbody>
                    </table>
                <?php else: ?>
                    <center>No se encontró el Ticket</center>
                <?php endif; ?>
	   		</div>
        </div>
    </div>
</div>