<?php use Zend\Db\Sql\Predicate\IsNull;
echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<meta name="mobile-web-app-capable" content="yes">
        <link rel="icon" sizes="196x196" href="ico-hres.png">
       <link rel="icon" sizes="128x128" href="ico-lres.png">
<link rel="icon" type="image/gif" href="<?php echo $this->basepath();?>/img/icoLogo.gif" />
        <?php echo $this->headTitle($this->translate('Sistema Integral de Parqueo'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
								
echo $this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' )->appendHttpEquiv ( 'X-UA-Compatible', 'IE=edge' )?>

        <!-- Le styles -->
        <?php
								
echo $this->headLink ( array (
					'rel' => 'shortcut icon',
					'type' => 'image/vnd.microsoft.icon',
					'href' => $this->basePath () . '/img/favicon.ico' 
					) )
					//->prependStylesheet ( $this->basePath () . '/css/style.css' )
					->prependStylesheet ( $this->basePath () . '/css/bootstrap-theme.min.css' )
					->prependStylesheet ( $this->basePath () . '/css/bootstrap.min.css' )
					->prependStylesheet ( $this->basePath () . '/css/login.css')
					?>

        <!-- Scripts -->
        <?php
								
echo $this->headScript ()
            		->prependFile($this->basePath() . '/js/jquery-validation/dist/jquery.validate.js')
					->prependFile ( $this->basePath () . '/js/bootstrap.min.js' )
					->prependFile ( $this->basePath () . '/js/jquery.min.js' )
					->prependFile ( $this->basePath () . '/js/respond.min.js', 'text/javascript', array (
															'conditional' => 'lt IE 9' 
													) )
					->prependFile ( $this->basePath () . '/js/html5shiv.js', 'text/javascript', array (
															'conditional' => 'lt IE 9' 
													) );
								?>
    <style type="text/css">
		body {
			overflow-x: hidden;
			/*background: #ee5d1f;*/
			background: #f3a600;
		}
	</style>


    <script>
    $('#myAlert').on('closed.bs.alert', function () {
  	  // do something…
  	})
    </script>

   </head>
    
<body>
<!-- 
	<div class="container-content-layout hidden-xs">&nbsp;</div>
	<div class="container-content-layout-xs visible-xs">&nbsp;</div>
	 -->
	<div style="background-color: #000000; width: 100%; height: 40px; color: #FFFFFF; font-weight: 700; padding-top: 10px; padding-left: 10px;">Sistema Integral de Parqueo</div>
	<div style="padding-top: 10px;">&nbsp;</div>
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <?php echo $this->content; //ejemplo ?>
            <div><br /><br /></div>
            <?php if(isset($this->mensaje) && !is_null($this->mensaje)):?>
            <div class="row col-md-6 col-md-offset-3 text-center">
    			<div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <strong>Error!</strong> <?php echo $this->mensaje; ?>
                </div>
            </div>
			<?php endif; ?>
	</div>
    
    </body>
</html>

