<?php
echo $this->doctype ();
use Application\Funciones\Funciones;
?>
<html>
<head>
<meta charset="utf-8">
        <link rel="icon" type="image/gif" href="<?php echo $this->basepath();?>/img/icoLogo.gif" />
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/font-awesome-4.1.0/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/js/datatables/media/css/demo_table.css')        
                        //->prependStylesheet($this->basePath() . '/css/docs.min.css')
        				//->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-1.10.4.custom.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        	//->prependFile($this->basePath() . '/js/jquery-ui/js/jquery-ui-1.10.4.custom.min.js')
        	->prependFile($this->basePath() . '/js/datatables/media/js/jquery.dataTables.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            //->prependFile($this->basePath() . '/js/jquery-ui-min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

</head>
<body>
	<div class="menu-top">&nbsp;</div>
      <?php
      
          echo $this->navigation('Navigation')
          ->menu()
          ->setPartial(array('partial/menu.phtml', 'Application'));
      ?>
	<div style="float: left; width: 200px;">
		<ul class="list-group">
		  <li class="list-group-item">Cras justo odio</li>
		  <li class="list-group-item">Dapibus ac facilisis in</li>
		  <li class="list-group-item">Morbi leo risus</li>
		  <li class="list-group-item">Porta ac consectetur ac</li>
		  <li class="list-group-item">Vestibulum at eros</li>
		</ul>
	</div>

		<div class="col-xs-12 col-sm-12 col-md-12">
    		<?php echo $this->content; ?>
    	</div>
    </body>
</html>