<?php
echo $this->doctype ();
//use Application\Funciones\Funciones;
?>
<html>
<head>
	<meta name="mobile-web-app-capable" content="yes">
<meta charset="utf-8">
        <link rel="icon" sizes="196x196" href="ico-hres.png">
       <link rel="icon" sizes="128x128" href="ico-lres.png">
        <link rel="icon" type="image/gif" href="<?php echo $this->basepath();?>/img/icoLogo.gif" />
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/font-awesome-4.1.0/css/font-awesome.min.css')
        				//->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-1.10.4.custom.css')
        				->prependStylesheet($this->basePath() . '/js/dataTable/media/css/jquery.dataTables_themeroller.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        
		?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/js/dataTables.bootstrap.js')
        	->prependFile($this->basePath() . '/js/dataTable/media/js/jquery.dataTables.min.js')
        	->prependFile($this->basePath() . '/js/bootstrap.min.js')
        	->prependFile($this->basePath() . '/js/jquery.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))

        ; ?>
        
	<script>
		 $(document).ready(function(){

	    	var table = $('.table').dataTable({
	    		aoColumnDefs: [
							{ bSortable: false, aTargets: [ 0 ] },
	    		            { bSortable: true, aTargets: [ '_all' ] }
	    		             ],
				"pagingType": "full_numbers",
				 "dom": '<"toolbar">frtip',
				 "order": [ 0, true ],
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ registros para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "",
					"oPaginate": {
						"sFirst":    "&laquo;",
						"sLast":     "&raquo;",
						"sNext":     "&gt;",
						"sPrevious": "&lt;"
					}
				}
	    	});
		}); 

		function eliminarRegistro(texto){
			if(confirm("¿Desea eliminar el registro '" + texto + "' ?")){
				return true;
			}else{
				return false;
			}

			return false;
		}
	</script>
</head>
<body>
	<div class="menu-top">&nbsp;</div>
      <?php
      
          echo $this->navigation('Navigation')
          ->menu()
          ->setPartial(array('partial/menu.phtml', 'Application'));
      ?>
		<div class="col-xs-12 col-sm-12 col-md-12">
    		<?php echo $this->content; ?>
    	</div>
    </body>
</html>
