<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Sistema Integral de Parqueaderos - SIP</title>
		<meta name="description" content="description">
		<meta name="author" content="SIP">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="mobile-web-app-capable" content="yes">
        <link rel="icon" sizes="196x196" href="ico-hres.png">
       <link rel="icon" sizes="128x128" href="ico-lres.png">
		<?php
								
        echo $this->headLink ( array (
					'rel' => 'shortcut icon',
					'type' => 'image/png',
					'href' => $this->basePath () . '/img/png/favicon.png' 
					) )
					
					->prependStylesheet ( $this->basePath () . '/css/style-old.css')
					->prependStylesheet ( $this->basePath () . '/css/style.css')
					->prependStylesheet ( $this->basePath () . '/js/dataTable/media/css/jquery.dataTables_themeroller.css')
					//->prependStylesheet ( $this->basePath () . '/plugins/select2/select2.css')
					//->prependStylesheet ( $this->basePath () . '/plugins/xcharts/xcharts.min.css')
					//->prependStylesheet ( $this->basePath () . '/plugins/fullcalendar/fullcalendar.css')
					//->prependStylesheet ( $this->basePath () . '/plugins/fancybox/jquery.fancybox.css')
					//->prependStylesheet ( 'http://fonts.googleapis.com/css?family=Righteous')
					->prependStylesheet ( $this->basePath() . '/css/font-awesome-4.1.0/css/font-awesome.min.css')
					->prependStylesheet ( $this->basePath () . '/plugins/jquery-ui/jquery-ui.min.css' )
					->prependStylesheet ( $this->basePath () . '/plugins/bootstrap/bootstrap.css' );
                    //->prependStylesheet ( $this->basePath () . '/css/bootstrap.css' )
        
        echo $this->headScript ()
                    ->prependFile ( $this->basePath () . '/js/respond.min.js', 'text/javascript', array ('conditional' => 'lt IE 9'	) )
                    ->prependFile ( $this->basePath () . '/js/html5shiv.js', 'text/javascript', array (	'conditional' => 'lt IE 9'	) )
                    ->prependFile ( $this->basePath () . '/js/dataTables.bootstrap.js')
                    ->prependFile ( $this->basePath () . '/js/dataTable/media/js/jquery.dataTables.min.js')
                    ->prependFile ( $this->basePath () . '/js/devoops.js' )
                    //->prependFile ( $this->basePath () . '/plugins/tinymce/jquery.tinymce.min.js' )
                    //->prependFile ( $this->basePath () . '/plugins/tinymce/tinymce.min.js' )
                    //->prependFile ( $this->basePath () . '/plugins/justified-gallery/jquery.justifiedgallery.min.js' )
                    ->prependFile ( $this->basePath () . '/plugins/bootstrap/bootstrap.min.js' )
                    ->prependFile ( $this->basePath () . '/plugins/jquery-ui/jquery-ui.min.js' )
                    ->prependFile ( $this->basePath () . '/plugins/jquery/jquery-2.1.0.min.js');
		?>
					<script>
		 $(document).ready(function(){

	    	var table = $('.table').dataTable({
	    		aoColumnDefs: [
							{ bSortable: false, aTargets: [ 0 ] },
	    		            { bSortable: true, aTargets: [ '_all' ] }
	    		             ],
				"pagingType": "full_numbers",
				 "dom": '<"toolbar">frtip',
				 "order": [ 0, true ],
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ registros para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "",
					"oPaginate": {
						"sFirst":    "&laquo;",
						"sLast":     "&raquo;",
						"sNext":     "&gt;",
						"sPrevious": "&lt;"
					}
				}
	    	});

			menuActive('<?php echo $this->menupadre; ?>', '<?php echo $this->menuhijo; ?>');

		}); 

		function eliminarRegistro(texto){
			if(confirm("¿Desea eliminar el registro '" + texto + "' ?")){
				return true;
			}else{
				return false;
			}

			return false;
		}

		function menuActive(padre, hijo){

			if(padre != null){
				$( '#' + padre ).trigger( 'click' );
			}
			
		    $( '#' + hijo ).attr( 'class','active' );
		}
	</script>
				
			<style>
	
		html, body {
	margin: 0 0;
			padding: 0 0;
}
	
	</style>		
					
	</head>
	
<body>
<!--Start Header-->
<header class="navbar">
	<div class="container-fluid expanded-panel">
		<div class="row">
			<div id="logo" class="col-xs-8 col-sm-8">
				<div style="float: left; padding-right: 10px;"><a href="index.html"><img src="<?php echo $this->basepath() . '/img/png/logo_sip.png'?>" width="80px" /> <span style="font-size: 12px;">(v1.0)</span></a></div>
				<div><a href="#" class="show-sidebar"><i class="fa fa-bars"></i></a></div>
			</div>
			<div id="top-panel" class="col-xs-4 col-sm-4">
				<div class="row">
					<div class="hidden-xs col-sm-6">
						<!-- 
						<div id="search">
							<input type="text" placeholder="search"/>
							<i class="fa fa-search"></i>
						</div>
						 -->
						 <ul class="nav navbar-nav pull-left panel-menu">
							<li class="hidden-xs">
								<a href="index.html" class="modal-link">
									<i class="fa fa-bell"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a class="ajax-link" href="ajax/calendar.html">
									<i class="fa fa-calendar"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a href="ajax/page_messages.html" class="ajax-link">
									<i class="fa fa-envelope"></i>
									<span class="badge">7</span>
								</a>
							</li>
						</ul>
					</div>
					<div class="col-xs-12 col-sm-6 top-panel-right">
						<ul class="nav navbar-nav pull-right panel-menu">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle account" data-toggle="dropdown">
									<div class="avatar">
									<img src="<?php echo $this->basepath() . '/img/avatar.jpg'?>" alt="avatar" class="img-circle" style="min-width: 43px !important;">
									</div>
									<i class="fa fa-ellipsis-v pull-right" style="color: #fff"></i>
									<div class="user-mini pull-right">
										<span class="welcome">Hola,</span>
										<span><?php
                                        echo $_SESSION['Zend_Auth']['storage']->usu_nombre . ' ';
                                        echo $_SESSION['Zend_Auth']['storage']->usu_apellido;
										?></span>
									</div>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">
											<i class="fa fa-user"></i>
											<span>Perfil</span>
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-cog"></i>
											<span>Configuraci&oacute;n</span>
										</a>
									</li>
									<li>
										<a href="<?php echo $this->url('application', array('controller'=>'login', 'action' => 'logout')) ?>">
											<i class="fa fa-power-off"></i>
											<span>Logout</span>
										</a>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<!--End Header-->
<!--Start Container-->
<div id="main">
		<div id="sidebar-left" class="col-xs-2 col-sm-2">
		
			<ul class="nav main-menu">
			    <li id="inicio">
					<a href="<?php echo $this->url('parametros', array('controller' => 'index', 'action' => 'video')) ?>" >
						<i class="fa fa-chevron-left"></i>
						<span class="hidden-xs">Inicio</span>
					</a>
				</li>
				<li id="dashboard">
					<a href="<?php echo $this->url('parametros', array('controller' => 'index', 'action' => 'index')) ?>">
						<i class="fa fa-dashboard"></i>
						<span class="hidden-xs">Dashboard</span>
					</a>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-cogs"></i>
						<span class="hidden-xs" id="parametros">Par&aacute;metros</span>
					</a>
					<ul class="dropdown-menu">
						<li id="paises"><a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action' => 'listado')) ?>"><i class="fa fa-globe fa-fw"></i> Paises</a></li>
						<li id="estados"><a href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action' => 'listado')) ?>"><i class="fa fa-building-o fa-fw"></i> Estados</a></li>
						<li id="ciudades"><a href="<?php echo $this->url('parametros', array('controller' => 'ciudad', 'action' => 'listado')) ?>"><i class="fa fa-flag-checkered fa-fw"></i> Ciudades</a></li>
						<li id="sectores"><a href="<?php echo $this->url('parametros', array('controller' => 'sector', 'action' => 'listado')) ?>"><i class="fa fa-location-arrow fa-fw"></i> Sectores</a></li>
						<li id="parqueaderos"><a href="<?php echo $this->url('parametros', array('controller' => 'parqueadero', 'action' => 'listado')) ?>"><i class="fa fa-map-marker fa-fw"></i> Parqueaderos</a></li>
						<li id="tipoInfraccion"><a href="<?php echo $this->url('parametros', array('controller' => 'tipoinfraccion', 'action' => 'listado')) ?>"><i class="fa fa-list fa-fw"></i> Tipo Infracci&oacute;n</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-group"></i>
						 <span class="hidden-xs" id="administracion">Administraci&oacute;n</span>
					</a>
					<ul class="dropdown-menu">
						<li id="usuarios"><a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'index')) ?>"><i class="fa fa-user fa-fw"></i> Usuarios</a></li>
						<li id="roles"><a href="<?php echo $this->url('usuarios', array('controller' => 'roles', 'action' => 'listado')) ?>"><i class="fa fa-random fa-fw"></i> Roles</a></li>
						<li id="aplicaciones"><a href="<?php echo $this->url('usuarios', array('controller' => 'aplicaciones', 'action' => 'listado')) ?>"><i class="fa fa-reorder fa-fw"></i> Aplicaciones</a></li>
						<li id="menus"><a href="<?php echo $this->url('usuarios', array('controller' => 'menu', 'action' => 'index')) ?>"><i class="fa fa-external-link fa-fw"></i> Men&uacute;s</a></li>
					</ul>
				</li>
				<li id="infracciones">
					 <a href="<?php echo $this->url('infraccion', array('controller' => 'infraccion', 'action' => 'index')) ?>">
						 <i class="fa fa-gavel"></i>
						 <span class="hidden-xs">Infracciones</span>
					</a>
				</li>
				 <li id="parqueaderodis">
					<a href="<?php echo $this->url('parqueaderos', array('controller' => 'parqueaderos', 'action' => 'index')) ?>">
						 <i class="fa fa-table"></i>
						 <span class="hidden-xs">Parqueaderos Disponibles</span>
					</a>
				 </li>
				  <li id="clientes">
					<a href="<?php echo $this->url('clientes', array('controller' => 'index', 'action' => 'listado')) ?>">
						 <i class="fa fa-child"></i>
						 <span class="hidden-xs">Clientes</span>
					</a>
				 </li>
				  <li id="comprasParqueo">
					<a href="<?php echo $this->url('clientes', array('controller' => 'compras', 'action' => 'transaccion')) ?>">
						 <i class="fa fa-dollar"></i>
						 <span class="hidden-xs">Compras de Parqueo</span>
					</a>
				 </li>
				 <li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-bar-chart-o"></i>
						<span class="hidden-xs" id="reportes">Reportes</span>
					</a>
					<ul class="dropdown-menu">
    					<li><a href="<?php echo $this->url('reportes', array('controller' => 'index', 'action' => 'index')) ?>">Float Charts</a></li>
						<li><a href="<?php echo $this->url('reportes', array('controller' => 'index', 'action' => 'xchart')) ?>">X Charts</a></li>
						<li><a href="<?php echo $this->url('reportes', array('controller' => 'index', 'action' => 'chartsgoogle')) ?>">Google Charts</a></li>
						<li><a href="<?php echo $this->url('reportes', array('controller' => 'index', 'action' => 'chartsmorris')) ?>">Morris Charts</a></li>
					</ul>
				</li>
			</ul>
		</div>
		<!--Start Content-->
		<div id="content" class="col-xs-12 col-sm-10">
		  <?php echo $this->content;?> 
		 </div>
		<!--End Content-->
</div>
</body>
</html>