<?php
//use Recetas\Model\Funciones\Fecha;

$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'estado',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' );
$formLabel = $this->plugin ( 'formLabel' );

$est_id = $form->get ( 'est_id' );
$pai_id = $form->get ( 'pai_id' );
$est_nombre_es = $form->get ( 'est_nombre_es' );
$est_nombre_en = $form->get ( 'est_nombre_en' );

//$date = new Fecha();

echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $est_id );
echo $this->formelementerrors ( $est_id );

?>
<div class="panel panel-default">
	<div class="panel-heading panel-heading-txt">&nbsp;</div>
		<table width="100%" cellpadding="5">
			<tr>
				<td colspan="3">
					<br />
					<div width="50" valign="middle" class="icon-content"><img src="<?php echo $this->basepath() . '/img/png/estado_grande.png'?>" border="0" /></div>
					<div class="txt-icon-content">Ingresar un nuevo estado<br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo estado.</div>
					<div><br /><hr /></div>
				</td>
			</tr>
			<tr>
				<td>
				<?php echo $formLabel->openTag() . $pai_id->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formselect ( $pai_id ) );
					  echo html_entity_decode( $this->formelementerrors ( $pai_id ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $est_nombre_es->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $est_nombre_es ) );
					  echo html_entity_decode( $this->formelementerrors ( $est_nombre_es ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $est_nombre_en->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $est_nombre_en ) );
					  echo html_entity_decode( $this->formelementerrors ( $est_nombre_en ) ); 
				?>
				</td>
			</tr>
		</table>
		<div><br /><hr /></div>	
		<div align="center">
				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				<a href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
			</div>	
		<div>&nbsp;</div>	
</div>
<?php echo $this->form()->closeTag(); ?>