 <?php $this->headTitle('Listado de Estados'); ?>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td>
			<div width="50" valign="middle" class="icon-content"><img src="<?php echo $this->basepath() . '/img/png/estado_grande.png'?>" border="0" /></div>
			<div class="txt-icon-content">Ingresar un nuevo estado<br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo estado.</div>
			<div><br /><hr /></div>
		</td>
	</tr>
</table>
 <div style="padding-bottom: 30px;">
     <a href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action'=>'ingresar'));?>" class="btn btn-primary">
     <img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar un nuevo registro</a>
 </div>
<div style=" padding-bottom: 100px;  ">
 <table class="table table-striped table-bordered table-hover" style="font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>&nbsp;</th>
 	 <th>Nombre Pa&iacute;s</th>
     <th>Nombre Espa&ntilde;ol</th>
     <th>Nombre Ingl&eacute;s</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->estado as $ciudad) : ?>
 <tr>
 	 <td width="150">
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action' => 'editar', 'id' => $ciudad->getEst_id()))?>" title="Actualizar" alt="Actualizar">Editar</a> |
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action' => 'eliminar', 'id' => $ciudad->getEst_id()))?>" title="Eliminar" alt="Eliminar">Eliminar</a>
 	 </td>
     <td><?php echo $this->escapeHtml($ciudad->getPai_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($ciudad->getEst_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($ciudad->getEst_nombre_en());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>