<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Estados</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                 	 <th>
                	 	 <a href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action'=>'ingresar'));?>" class="btn btn-primary">
                	     <i class="fa fa-plus-circle"></i> Nuevo</a>
                     </th>
                 	 <th>Nombre Pa&iacute;s</th>
                     <th>Nombre Espa&ntilde;ol</th>
                     <th>Nombre Ingl&eacute;s</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                 foreach ($this->estado as $ciudad) : ?>
                 <tr>
                 	 <td class="dataTableIcons">
                 	 	<a class="fa-lg" href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action' => 'editar', 'id' => $ciudad->getEst_id()))?>"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp;
                 	 	<a class="fa-lg" href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action' => 'eliminar', 'id' => $ciudad->getEst_id()))?>" onclick="return eliminarRegistro('<?php echo $ciudad->getEst_nombre_es() ?>');"><i class="fa fa-trash-o"></i></a>
                 	 </td>
                     <td><?php echo $this->escapeHtml($ciudad->getPai_nombre_es());?></td>
                     <td><?php echo $this->escapeHtml($ciudad->getEst_nombre_es());?></td>
                     <td><?php echo $this->escapeHtml($ciudad->getEst_nombre_en());?></td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
				
			</div>
        </div>
    </div>
</div>