<div class="titulo-ventana"><i class="fa fa-gears fa-fw"></i> Par&aacute;metros - Listado de Estados</div>
<hr class="hr-style" />

 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th>
	 	 <a href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action'=>'ingresar'));?>" class="btn btn-primary">
	     <i class="fa fa-plus-circle"></i> Nuevo</a>
     </th>
 	 <th>Nombre Pa&iacute;s</th>
     <th>Nombre Espa&ntilde;ol</th>
     <th>Nombre Ingl&eacute;s</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->estado as $ciudad) : ?>
 <tr>
 	 <td width="7%" style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action' => 'editar', 'id' => $ciudad->getEst_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('parametros', array('controller' => 'estado', 'action' => 'eliminar', 'id' => $ciudad->getEst_id()))?>" onclick="return eliminarRegistro('<?php echo $ciudad->getEst_nombre_es() ?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
     <td><?php echo $this->escapeHtml($ciudad->getPai_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($ciudad->getEst_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($ciudad->getEst_nombre_en());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
