<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); 

$form = $this->form;
$detalles = $this->detalles;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'usuarios', array (
		'controller' => 'roles',
		'action' => 'validar' 
) ) );

$form->setAttribute ( 'method', 'post' )
->setAttribute ('class', 'form-horizontal');
$formLabel = $this->plugin ( 'formLabel' );

$rol_descripcion = $form->get('rol_descripcion');
$rol_id = $form->get('rol_id');
$aplicacion = $form->get('aplicacion');

echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $rol_id );
echo $this->formelementerrors ( $rol_id );
?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span><?php echo $this->titulo ?> rol</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Ingrese la informaci&oacute;n solicitada. Todos los campos con * son obligatorios.</label>
        			</div>
    			</div>
    			<div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1">
                        <?php  
                		echo $formLabel->openTag() . $rol_descripcion->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-md-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $rol_descripcion ) );
					    echo html_entity_decode( $this->formelementerrors ( $rol_descripcion ) ); 
            			?>
            		</div>
                </div>
                <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Seleccione los permisos a los que puede acceder el rol.</label>
        			</div>
    			</div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
            			<?php 
            			$aplicacion = $form->get('aplicacion');
            			echo html_entity_decode($this->formmulticheckbox($aplicacion));
		                echo html_entity_decode($this->formelementerrors($aplicacion));
            			?>
            		</div>
                </div>
                <div class="row">
    				<div class="form-group col-md-12">
            		     <div align="center">
            				<?php echo $this->formRow($form->get('ingresar')); ?>&nbsp;
	                        <a href="<?php echo $this->url('usuarios', array('controller' => 'roles', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
            			</div>	
        			</div>
    			</div>
			</div>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>

<script type="text/javascript">
							/*
	$(document).ready(function(){
		//Inicio Bloque Validador JS
		$.validator.addMethod("roles", function(value, elem, param) {
		    if($(".roles:checkbox:checked").length > 0){
		    	return true;
		   	}else {
		    	return false;
		   	}
		},"Debes seleccionar al menos una opción");


		$("#roles").validate({
			errorLabelContainer: $("ul.error_container"),
			wrapper: 'li',
			rules: {
				rol_descripcion: {
					required:true,
					remote: {
        				url: "<?php //echo $this->url('usuarios',array('controller'=>'usuarios','action'=>'consultaNombreRolXmlHttp'))?>",
        				type: "post",
        				data: {
          					rol_id: function() {
            					return $( "#rol_id" ).val();
          					}
        				}
      				}
				},
				"APLICACION[1][APL_ID]" :{
					roles:true
				}
	 		},
	 		messages:{
				rol_descripcion: {
					required:'Nombre es un campo requerido',
					remote: 'El nombre seleccionado ya se encuentra en el sistema'},
				}
		});
	});
	*/
</script>