<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Roles</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
                 <table class="table table-striped table-hover" style="font-size: 12px;" >
                 <thead>
                 <tr>
                 	 <th width="7%">
                 	 	<a href="<?php echo $this->url('usuarios', array('controller' => 'roles', 'action'=>'ingresar'));?>" class="btn btn-primary">
                     	<i class="fa fa-plus-circle"></i> Nuevo</a>
                 	 </th>
                     <th>Descripci&oacute;n</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                 foreach ($this->roles as $menu) : ?>
                 <tr>
                 	 <td class="dataTableIcons">
                 	 	<a class="fa-lg" href="<?php echo $this->url('usuarios', array('controller' => 'roles', 'action' => 'editar', 'id' => $menu->getRol_id()))?>"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp;
                 	 	<a class="fa-lg" href="<?php echo $this->url('usuarios', array('controller' => 'roles', 'action' => 'eliminar', 'id' => $menu->getRol_id()))?>" onclick="return eliminarRegistro('<?php echo $menu->getRol_descripcion()?>');"><i class="fa fa-trash-o"></i></a>
                 	 </td>
                     <td><?php echo $this->escapeHtml($menu->getRol_descripcion());?></td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
			</div>
        </div>
    </div>
</div>