<div class="titulo-ventana"><i class="fa fa-users fa-fw"></i> Administraci&oacute;n - Listado de Roles</div>
<hr class="hr-style" />

 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th width="7%">
 	 	<a href="<?php echo $this->url('usuarios', array('controller' => 'roles', 'action'=>'ingresar'));?>" class="btn btn-primary">
     	<i class="fa fa-plus-circle"></i> Nuevo</a>
 	 </th>
     <th>Descripci&oacute;n</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->roles as $roles) : ?>
 <tr>
 	 <td style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('usuarios', array('controller' => 'roles', 'action' => 'editar', 'id' => $roles->getRol_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('usuarios', array('controller' => 'roles', 'action' => 'eliminar', 'id' => $roles->getRol_id()))?>" onclick="return eliminarRegistro('<?php echo $roles->getRol_descripcion()?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
     <td><?php echo $this->escapeHtml($roles->getRol_descripcion());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>