 <?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>
<?php 

    $form = $this->formulario;
    $form->prepare ();
    $form->setAttribute ( 'action', $this->url ( 'infraccion', array (
            'controller' => 'infraccion',
            'action' => 'consulta' 
    ) ) )->setAttribute ( 'method', 'post' )
    ->setAttribute ('class', 'form-horizontal');
    $formLabel = $this->plugin ( 'formLabel' );

    $placa  =   $form->get('placa');
    
 ?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Infracciones</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">

                
                <div class="row">
                    <?php echo $this->form ()->openTag ( $form ); ?>

                    <div class="control-label col-md-2 col-lg-2 ">
                        <?php  
                            echo $formLabel->openTag() . $placa->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <?php 
                        echo html_entity_decode( $this->formtext ( $placa ) );
                        echo html_entity_decode( $this->formelementerrors ( $placa ) );
                        ?>
                    </div>
                    <div class="control-label col-md-2 col-lg-2 ">
                        <?php echo $this->formsubmit( $form->get ( 'buscar' ) ) ?>
                    </div>

                    <?php echo $this->form()->closeTag(); ?>
                </div>


                <?php if(sizeof($this->infracciones)>0): ?>
                    <table class="table table-striped table-hover" style="font-size: 12px;" >
                        <thead>
                        <tr>
                            <th>N&uacute;mero</th>
                            <th>Calles</th>
                            <th>Fecha</th>
                            <th>Hora</th>
                            <th>Valor</th>
                        </tr>
                        </thead>
                        <tbody>
                            
                            <?php foreach($this->infracciones as $infraccion): ?>
                            <tr>
                                <td><?php echo $infraccion->numero ?></td>
                                <td><?php echo $infraccion->calles ?></td>
                                <td><?php echo $infraccion->fecha ?></td>
                                <td><?php echo $infraccion->hora ?></td>
                                <td><?php echo $infraccion->valor ?></td>
                            </tr>
                            <?php endforeach; ?>
                               
                        </tbody>
                    </table>
                <?php else: ?>
                    <center>No se encontraron Infracciones</center>
                <?php endif; ?>
	   		</div>
        </div>
    </div>
</div>