<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>
<?php 

    $form = $this->formulario;
    $form->prepare ();
    $form->setAttribute ( 'action', $this->url ( 'infraccion', array (
            'controller' => 'infraccion',
            'action' => 'aprobar_infraccion',
            'id' => $this->infraccion->getInf_id()
    ) ) )->setAttribute ( 'method', 'post' )
    ->setAttribute ('class', 'form-horizontal');
    $formLabel = $this->plugin ( 'formLabel' );

    $inmovilizado  =   $form->get('inmovilizado');
    $tiempo_permanencia  =   $form->get('tiempo_permanencia');

?>
<?php echo $this->form ()->openTag ( $form ); ?>
<ul class="messages">
    <?php foreach($this->messages as $message):  ?>
        <li><?php echo  $message; ?></li>
    <?php endforeach; ?>
</ul>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-eye fa-fw"></i>
					<span>Aprobar Infracción</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">

			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Verifique la infracción cometida.</label>
        			</div>
    			</div>

                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <b>Tipo:</b>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                			<?php 
                			echo $this->escapeHtml($this->tipo->getTip_inf_descripcion());
                			?>
            		    </div>
        		    </div>
            	</div>

                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <b>Fecha y Hora:</b>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                            <?php 
                            echo $this->infraccion->getInf_fecha();
                            ?>
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <b>Nombre del Agente:</b>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                            <?php 
                            echo $this->usuario->getUsu_nombre().' '.$this->usuario->getUsu_apellido();
                            ?>
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <b>Lugar:</b>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                        Parqueadero Nro. <?php  echo $this->multa->getPar_id(); ?>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <b>Direcci&oacute;n:</b>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                <?php  echo $this->calle_principal->getCal_nombre(); ?> y <?php echo $this->calle_secundaria->getCal_nombre(); ?>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $inmovilizado->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formselect ( $inmovilizado ) );
                        echo html_entity_decode( $this->formelementerrors ( $inmovilizado ) );
                        ?>
                    </div>
                </div>    
                <div class="form-group row">    
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                            echo $formLabel->openTag() . $tiempo_permanencia->getLabel() . $formLabel->closeTag();
                        ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <?php 
                        echo html_entity_decode( $this->formselect ( $tiempo_permanencia ) );
                        echo html_entity_decode( $this->formelementerrors ( $tiempo_permanencia ) );
                        ?>
                    </div>
                </div>        
			</div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-eye fa-fw"></i>
                    <span>Evidencias</span>
                </div>
                <div class="box-icons hidden-xs">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content">
            <?php if($this->multa->getMul_par_prueba_1()!=''): ?>
                <img src="http://ibarra.sip.ec/Violations/files/<?php echo $this->multa->getMul_par_prueba_1(); ?>" alt="" width="300">
            <?php endif; ?>
            <?php if($this->multa->getMul_par_prueba_2()!=''): ?>
                <img src="http://ibarra.sip.ec/Violations/files/<?php echo $this->multa->getMul_par_prueba_2(); ?>" alt="" width="300">
            <?php endif; ?>
            <?php if($this->multa->getMul_par_prueba_3()!=''): ?>
                <img src="http://ibarra.sip.ec/Violations/files/<?php echo $this->multa->getMul_par_prueba_3(); ?>" alt="" width="300">
            <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group col-md-12">
         <div align="center">

            <?php echo $this->formsubmit( $form->get ( 'buscar' ) ) ?>

            <a class="btn btn-primary" onclick="return confirm('Está seguro de que desea rechazar esta infracción? No podr/aacute; aprobarla m&aacute;s adelante')" href="<?php echo $this->url('infraccion', array('controller' => 'infraccion', 'action' => 'rechazar_infraccion', 'id' => $this->infraccion->getInf_id()))?>">Rechazar Infracci&oacute;n</a>

            <a href="<?php echo $this->url('infraccion', array('controller' => 'infraccion')); ?>" class ="btn btn-primary" >Cancelar</a>
        </div>  
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>