<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); 

?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-eye fa-fw"></i>
					<span>Aprobar Infracción</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1">
            		  <label class="control-label" style="color: #ee9f1f;">Verifique la infracción cometida.</label>
        			</div>
    			</div>

                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <b>Tipo:</b>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                			<?php 
                			echo $this->escapeHtml($this->tipo->getTip_inf_descripcion());
                			?>
            		    </div>
        		    </div>
            	</div>

                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <b>Fecha y Hora:</b>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                            <?php 
                            echo $this->infraccion->getInf_fecha();
                            ?>
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <b>Nombre del Agente:</b>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                            <?php 
                            echo $this->usuario->getUsu_nombre().' '.$this->usuario->getUsu_apellido();
                            ?>
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <b>Lugar:</b>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                        <?php foreach($this->multa as $multa): ?>
                            Parqueadero Nro. <?php  echo $multa->getPar_id(); ?>
                        <?php endforeach; ?>
                        </div>
                    </div>
                </div>

			</div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-eye fa-fw"></i>
                    <span>Evidencias</span>
                </div>
                <div class="box-icons hidden-xs">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content">
                
                

                

            </div>
        </div>
    </div>
</div>