<?php //historial.phtml ?>
<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Historial de Infracciones</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">

                       <?php echo $this->mensaje; ?> 

                     <table class="table table-striped table-hover" style="font-size: 12px;" >
                     <thead>
                     <tr>
                        <th class="hidden-xs">Fecha</th>
                     	<th><span class="hidden-xs">Tipo de </span>Infracci&oacute;n</th>
                        <th>Placa</th>
                        <th>Estado</th>
                     </tr>
                     </thead>
                     <tbody>
                     <?php  foreach ($this->infraccion as $infraccion): ?>
                     <tr>
                         <td class="hidden-xs"><?php echo $this->escapeHtml($infraccion->getInf_fecha());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getTip_inf_descripcion());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getAut_placa());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getInf_estado())=='A'?'Aprobada':'Rechazada';?></td>
                     </tr>
                     <?php  endforeach; ?>
                     </tbody>
                     </table>
			</div>
        </div>
    </div>
</div>