<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Listado de Infracciones</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
                     <table class="table table-striped table-hover" style="font-size: 12px;" >
                     <thead>
                     <tr>
                         <th>&nbsp;</th>
                     	 <th>Tipo de Infracci&oacute;n</th>
                         <th>Placa</th>
                         <th>Fecha</th>
                         <th>Pa&iacute;s</th>
                         <th>Estado</th>
                         <th>Ciudad</th>
                         <th>Sector</th>
                         <th>Vigilante</th>
                     </tr>
                     </thead>
                     <tbody>
                     <?php 
                     foreach ($this->infraccion as $infraccion) : ?>
                     <tr>
                         <td style="text-align: center;"><a href="<?php echo $this->url('infraccion', array('controller' => 'infraccion', 'action' => 'detalle'))?>"><i class="fa fa-gavel fa-fw"></i></a></td>
                         <td><?php echo $this->escapeHtml($infraccion->getTip_inf_descripcion());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getInf_detalles());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getInf_fecha());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getPai_nombre_es());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getEst_nombre_es());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getCiu_nombre_es());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getSec_nombre());?></td>
                         <td><?php echo $this->escapeHtml($infraccion->getUsu_nombre() . ' ' . $infraccion->getUsu_apellido);?></td>
                     </tr>
                     <?php endforeach; ?>
                     </tbody>
                     </table>
			</div>
        </div>
    </div>
</div>