<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>
<?php 

	$form = $this->formulario;
	$form->prepare ();
	$form->setAttribute ( 'action', $this->url ( 'infraccion', array (
			'controller' => 'infraccion',
			'action' => 'reporte' 
	) ) )->setAttribute ( 'method', 'post' )
	->setAttribute ('class', 'form-horizontal');
	$formLabel = $this->plugin ( 'formLabel' );

	$fecha_ini	=	$form->get('fecha_ini');
	$fecha_fin  =   $form->get('fecha_fin');

 ?>
<?php echo $this->message; ?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span>Reporte de Infracciones</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">

				<div class="row">
					<?php echo $this->form ()->openTag ( $form ); ?>

					<div class="control-label col-md-2 col-lg-2 ">
	                    <?php  
	                		echo $formLabel->openTag() . $fecha_ini->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $fecha_ini ) );
            			echo html_entity_decode( $this->formelementerrors ( $fecha_ini ) );
            			?>
            		</div>
					<div class="control-label col-md-2 col-lg-2 ">
	                    <?php  
	                		echo $formLabel->openTag() . $fecha_fin->getLabel() . $formLabel->closeTag();
	                	?>
                	</div>
                	<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $fecha_fin ) );
            			echo html_entity_decode( $this->formelementerrors ( $fecha_fin ) );
            			?>
            		</div>
					<div class="control-label col-md-2 col-lg-2 ">
	                    <?php echo $this->formsubmit( $form->get ( 'buscar' ) ) ?>
                	</div>

					<?php echo $this->form()->closeTag(); ?>
				</div>




				<div class="row">
					<div class="col-lg-6">
	                     <table class="table table-striped table-hover" style="font-size: 12px;" >
	                     <thead>
	                     <tr>
	                     	<th>Tipo de Infracci&oacute;n</th>
	                        <th>Total</th>
	                     </tr>
	                     </thead>
	                     <tbody>
	                     <?php  $data_js=''; ?>
	                     <?php  foreach ($this->registros as $fila): ?>
	                     <tr>
	                     	<td> <?php echo $fila['tip_inf_codigo'].'. '.$fila['tip_inf_descripcion']; ?> </td>
	                     	<td> <?php echo $fila['total']; ?> </td>
	                     </tr>
	                     <?php  $data_js .= "{
			                name: '{$fila['tip_inf_codigo']}.',
			                y: {$fila['total']}
			                },"; ?>
	                     <?php  endforeach; ?>
	                     </tbody>
	                     </table>
                    </div>	
                    <div class="col-lg-6">
                    	<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
                    </div>	
				</div>
				<div class="row">
					<div class="col-lg-6">
						
						<table class="table table-striped table-hover" style="font-size: 12px;" >
	                     <thead>
	                     <tr>
	                     	<th>Vigilante</th>
	                        <th>Total</th>
	                     </tr>
	                     </thead>
	                     <tbody>
	                     <?php  foreach ($this->registros_vigilante as $fila): ?>
	                     <tr>
	                     	<td> <?php echo $fila['usu_nombre'].' '.$fila['usu_apellido']; ?> </td>
	                     	<td> <?php echo $fila['total']; ?> </td>
	                     </tr>
	                     <?php  endforeach; ?>
	                     </tbody>
	                     </table>
					</div>

					<div class="col-lg-6">	
						<table class="table table-striped table-hover" style="font-size: 12px;" >
	                     <thead>
	                     <tr>
	                     	<th>Calle</th>
	                        <th>Total</th>
	                     </tr>
	                     </thead>
	                     <tbody>
	                     <?php  foreach ($this->registros_calle as $fila): ?>
	                     <tr>
	                     	<td> <?php echo $fila['cal_nombre']; ?> </td>
	                     	<td> <?php echo $fila['total']; ?> </td>
	                     </tr>
	                     <?php  endforeach; ?>
	                     </tbody>
	                     </table>
					</div>
				</div>	
			</div>
        </div>
    </div>
</div>

<script type="text/javascript">
	$(function () {
	    $('#container').highcharts({
	        chart: {
	            plotBackgroundColor: null,
	            plotBorderWidth: null,
	            plotShadow: false,
	            type: 'pie'
	        },
	        title: {
	            text: 'Infracciones por Tipo'
	        },
	        tooltip: {
	            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
	        },
	        plotOptions: {
	            pie: {
	                allowPointSelect: true,
	                cursor: 'pointer',
	                dataLabels: {
	                    enabled: true,
	                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
	                    style: {
	                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
	                    }
	                }
	            }
	        },
	        series: [{
	            name: 'Brands',
	            colorByPoint: true,
	            data: [
	            	<?php echo $data_js; ?>
	            ]
	        }]
	    });
	});
</script>