<?php $this->headTitle('Ingresar Sitio - Actualizar Sitio');

//FORMULARIO
$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'tipoinfraccion',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' );
$formLabel = $this->plugin ( 'formLabel' );

$tip_inf_id = $form->get ( 'tip_inf_id' );
$tip_inf_descripcion = $form->get ( 'tip_inf_descripcion' );

//EMPIEZA A ESCRIBIRSE EL FORMULARIO
echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $tip_inf_id );
echo $this->formelementerrors ( $tip_inf_id );

?>
<div class="panel panel-default">
	<div class="panel-heading panel-heading-txt">&nbsp;</div>
		<table width="100%" cellpadding="5">
			<tr>
				<td colspan="3">
					<br />
					<div width="50" valign="middle" class="icon-content"><img src="<?php echo $this->basepath() . '/img/png/pais_grande.png'?>" border="0" /></div>
					<div class="txt-icon-content">Ingresar un nuevo tipo de infraccion<br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo tipo de infraccion.</div>
					<div><br /><hr /></div>
				</td>
			</tr>
			<tr>
				<td>
				<?php echo $formLabel->openTag() . $tip_inf_descripcion->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext( $tip_inf_descripcion ) );
					  echo html_entity_decode( $this->formelementerrors ( $tip_inf_descripcion ) ); 
				?>
				</td>
				<td colspan="2">&nbsp;</td>
			</tr>
			
		</table>
		<div><br /><hr /></div>	
		<div align="center"> 
				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				<a href="<?php echo $this->url('parametros', array('controller' => 'tipoinfraccion', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
			</div>	
		<div>&nbsp;</div>	
</div>
<?php echo $this->form()->closeTag(); ?>