<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); 

//FORMULARIO
$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'pais',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' )
->setAttribute ('class', 'form-horizontal');
$formLabel = $this->plugin ( 'formLabel' );

$pai_id = $form->get ( 'pai_id' );
$pai_nombre_es = $form->get ( 'pai_nombre_es' );
$pai_nombre_en = $form->get ( 'pai_nombre_en' );
$pai_codigo_telefono = $form->get ( 'pai_codigo_telefono' );

//EMPIEZA A ESCRIBIRSE EL FORMULARIO
echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $pai_id );
echo $this->formelementerrors ( $pai_id );
?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-12" >
        <div class="box">
            <div class="box-header">
				<div class="box-name">
					<i class="fa fa-gears fa-fw"></i>
					<span><?php echo $this->titulo ?> pa&iacute;s</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
			    <div class="row" style="padding-bottom: 12px;">
        			<div class="col-md-11 col-md-offset-1 col-xs-12">
            		  <label class="control-label" style="color: #ee9f1f; text-align: left !important;">Ingrese la informaci&oacute;n solicitada. Todos los campos con * son obligatorios.</label>
        			</div>
    			</div>
    			<div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php  
                		echo $formLabel->openTag() . $pai_nombre_es->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pai_nombre_es ) );
        			    echo html_entity_decode( $this->formelementerrors ( $pai_nombre_es ) ); 
            			?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $pai_nombre_en->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            			<?php 
            			echo html_entity_decode( $this->formtext ( $pai_nombre_en ) );
        				echo html_entity_decode( $this->formelementerrors ( $pai_nombre_en ) ); 
            			?>
            		</div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2 col-md-offset-1 col-lg-2 col-lg-offset-1">
                        <?php 
                		echo $formLabel->openTag() . $pai_codigo_telefono->getLabel() . $formLabel->closeTag();
                	   ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <div class="input-group">
                            <div class="input-group-addon">&nbsp;+&nbsp;</div>
                			<?php 
                			echo html_entity_decode( $this->formtext ( $pai_codigo_telefono ) );
            				echo html_entity_decode( $this->formelementerrors ( $pai_codigo_telefono ) );  
                			?>
                		    </div>
            		    </div>
                </div>
                <div class="row">
    				<div class="form-group col-md-12">
            		     <div align="center">
            				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
        				    <a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
            			</div>	
        			</div>
    			</div>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
