<?php $this->headTitle('Ingresar Paises - Actualizar Paises');

//FORMULARIO
$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'parametros', array (
		'controller' => 'pais',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' );
$formLabel = $this->plugin ( 'formLabel' );

$pai_id = $form->get ( 'pai_id' );
$pai_nombre_es = $form->get ( 'pai_nombre_es' );
$pai_nombre_en = $form->get ( 'pai_nombre_en' );
$pai_codigo_telefono = $form->get ( 'pai_codigo_telefono' );

//EMPIEZA A ESCRIBIRSE EL FORMULARIO
echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $pai_id );
echo $this->formelementerrors ( $pai_id );

?>
<div class="panel panel-default">
	<div class="panel-heading panel-heading-txt">&nbsp;</div>
		<table width="100%" cellpadding="5">
			<tr>
				<td colspan="3">
					<br />
					<div width="50" valign="middle" class="icon-content"><img src="<?php echo $this->basepath() . '/img/png/pais_grande.png'?>" border="0" /></div>
					<div class="txt-icon-content">Ingresar un nuevo pa&iacute;s<br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo pa&iacute;s.</div>
					<div><br /><hr /></div>
				</td>
			</tr>
			<tr>
				<td>
				<?php echo $formLabel->openTag() . $pai_nombre_es->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $pai_nombre_es ) );
					  echo html_entity_decode( $this->formelementerrors ( $pai_nombre_es ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $pai_nombre_en->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $pai_nombre_en ) );
					  echo html_entity_decode( $this->formelementerrors ( $pai_nombre_en ) ); 
				?>
				</td>
				<td>
				<?php echo $formLabel->openTag() . $pai_codigo_telefono->getLabel() . $formLabel->closeTag();
				      echo html_entity_decode( $this->formtext ( $pai_codigo_telefono ) );
					  echo html_entity_decode( $this->formelementerrors ( $pai_codigo_telefono ) ); 
				?>
				</td>
			</tr>
		</table>
		<div><br /><hr /></div>	
		<div align="center">
				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				<a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
			</div>	
		<div>&nbsp;</div>	
</div>
<?php echo $this->form()->closeTag(); ?>