<div class="titulo-ventana">Par&aacute;metros - Listado de Pa&iacute;ses</div>
<hr class="hr-style" />
 
 <div id="btn-ingresar" style="padding-bottom: 0px;">
     <a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action'=>'ingresar'));?>" class="btn btn-primary">
     <img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar un nuevo registro</a>
 </div>
 
 <table id="table" class="table table-striped table-bordered table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th>&nbsp;</th>
     <th>Nombre Espa&ntilde;ol</th>
     <th>Nombre Ingl&eacute;s</th>
     <th>C&oacute;digo de Tel&eacute;fono</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->pais as $estado) : ?>
 <tr>
 	 <td width="150">
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action' => 'editar', 'id' => $estado->getPai_id()))?>" title="Actualizar" alt="Actualizar">Editar</a> |
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action' => 'eliminar', 'id' => $estado->getPai_id()))?>" title="Eliminar" alt="Eliminar">Eliminar</a>
 	 </td>
     <td><?php echo $this->escapeHtml($estado->getPai_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($estado->getPai_nombre_en());?></td>
     <td><?php echo $this->escapeHtml($estado->getPai_codigo_telefono());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
<script>
		 $(document).ready(function(){

	    	var table = $('.table').dataTable({
				"pagingType": "full_numbers",
				 "dom": '<"toolbar">frtip',
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
	    	});

	     
		}); 
</script>