<div class="titulo-ventana"><i class="fa fa-gears fa-fw"></i> Par&aacute;metros - Listado de Pa&iacute;ses</div>
<hr class="hr-style" />
 
 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th> 
	    <a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action'=>'ingresar'));?>" class="btn btn-primary">
	    <i class="fa fa-plus-circle"></i> Nuevo</a>
 	 </th>
     <th>Nombre Espa&ntilde;ol</th>
     <th>Nombre Ingl&eacute;s</th>
     <th>C&oacute;digo de Tel&eacute;fono</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->pais as $estado) : ?>
 <tr>
 	 <td width="7%" style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action' => 'editar', 'id' => $estado->getPai_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action' => 'eliminar', 'id' => $estado->getPai_id()))?>" onclick="return eliminarRegistro('<?php echo $estado->getPai_nombre_es()?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
     <td><?php echo $this->escapeHtml($estado->getPai_nombre_es());?></td>
     <td><?php echo $this->escapeHtml($estado->getPai_nombre_en());?></td>
     <td><?php echo $this->escapeHtml($estado->getPai_codigo_telefono());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
