<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i> <span class="hidden-xs">Ingresos,
						Infracciones y Gastos</span> <span
						class="visible-xs-inline-block hidden-sm hidden-md hidden-lg">Estad&iacute;sticas</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link"> <i class="fa fa-chevron-up"></i>
					</a> <a class="expand-link"> <i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="display: inline-block; width: 100% !important;">
				<div class="col-xs-4 col-sm-4 col-lg-4">
					<div class="sparkline-dashboard" id="sparkline-1"></div>
					<div class="sparkline-dashboard-info">
						<i class="fa fa-usd"></i>756.45M <span class="txt-primary">Ingresos</span>
					</div>
				</div>
				<div class="col-xs-4 col-sm-4 col-lg-4">
					<div class="sparkline-dashboard" id="sparkline-2"></div>
					<div class="sparkline-dashboard-info">
						<i class="fa fa-usd"></i>245.12M <span class="txt-info">Gastos</span>
					</div>
				</div>
				<div class="col-xs-4 col-sm-4 col-lg-4">
					<div class="sparkline-dashboard" id="sparkline-3"></div>
					<div class="sparkline-dashboard-info">
						<i class="fa fa-usd"></i>245.12M <span class="">Utilidades</span>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-12" style="min-height: 100px;">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i> <span>Compras de parqueo</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link"> <i class="fa fa-chevron-up"></i>
					</a> <a class="expand-link"> <i class="fa fa-expand"></i>
					</a>
				</div>
			     <div class="no-move"></div>
			</div>
			<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-12" style="min-height: 100px;">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i> <span>Clientes</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link"> <i class="fa fa-chevron-up"></i>
					</a> <a class="expand-link"> <i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
				<div id="container3" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-12" style="min-height: 100px;">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i> <span>Clientes</span>
				</div>
				<div class="box-icons hidden-xs">
					<a class="collapse-link"> <i class="fa fa-chevron-up"></i>
					</a> <a class="expand-link"> <i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content" style="min-height: 80px;">
				<div id="container2" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
// Array for random data for Sparkline
var sparkline_arr_1 = SparklineTestData();
var sparkline_arr_2 = SparklineTestData();
var sparkline_arr_3 = SparklineTestData();
$(document).ready(function() {
	// Make all JS-activity for dashboard
	DashboardTabChecker();
	// Load Knob plugin and run callback for draw Knob charts for dashboard(tab-servers)
	LoadKnobScripts(DrawKnobDashboard);
	// Load Sparkline plugin and run callback for draw Sparkline charts for dashboard(top of dashboard + plot in tables)
	LoadSparkLineScript(DrawSparklineDashboard);
	// Load Morris plugin and run callback for draw Morris charts for dashboard
	LoadMorrisScripts(MorrisDashboard);
	// Make beauty hover in table
	$("#ticker-table").beautyHover();
});
</script>
<script type="text/javascript">
$(function () {
    $(document).ready(function () {
        Highcharts.setOptions({
            global: {
                useUTC: false
            }
        });

        $('#container').highcharts({
            chart: {
                type: 'spline',
                animation: Highcharts.svg, // don't animate in old IE
                marginRight: 10,
                events: {
                    load: function () {

                        // set up the updating of the chart each second
                        var series = this.series[0];
                        setInterval(function () {
                            var x = (new Date()).getTime(), // current time
                                y = Math.random();
                            series.addPoint([x, y], true, true);
                        }, 1000);
                    }
                }
            },
            title: {
                text: 'Compras de parqueo'
            },
            xAxis: {
                type: 'datetime',
                tickPixelInterval: 150
            },
            yAxis: {
                title: {
                    text: 'Pago realizado'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function () {
                    return '<b>' + this.series.name + '</b><br/>' +
                        Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>' +
                        Highcharts.numberFormat(this.y, 2);
                }
            },
            legend: {
                enabled: false
            },
            exporting: {
                enabled: false
            },
            series: [{
                name: 'Informacion',
                data: (function () {
                    // generate an array of random data
                    /* var data = [],
                        time = (new Date()).getTime(),
                        i;

                     for (i = -19; i <= 0; i += 1) {
                        data.push({
                            x: time + i * 500,
                            y: Math.random()
                        });
                    }  */

                	var data = [],
                	date = new Date();
                    time = (new Date()).getTime();

                    //alert(time);

                    data.push({x: time + -10 * 500, y: 0.5});
                    data.push({x: time + -9 * 500, y: 1.0});
                    data.push({x: time + -8 * 500, y: 0.5});
                    data.push({x: time + -7 * 500, y: 1.5});
                    data.push({x: time + -6 * 500, y: 1.0});
                    data.push({x: time + -5 * 500, y: 1.5});
                    data.push({x: time + -4 * 500, y: 0.5});
                    data.push({x: time + -3 * 500, y: 1.5});
                    data.push({x: time + -2 * 500, y: 1.0});
                    data.push({x: time + -1 * 500, y: 0.5}); 
                    data.push({x: time + 0 * 500, y: 1.0});
                    
                    return data;
                }())
            }]
        });
    });
});
		</script>
				<script type="text/javascript">
$(function () {
    $('#container2').highcharts({
        title: {
            text: 'Ingresos mensuales por ciudad',
            x: -20 //center
        },
        subtitle: {
            text: 'Ciudad: Todas / Año: 2014',
            x: -20
        },
        xAxis: {
            categories: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun',
                'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
        },
        yAxis: {
            title: {
                text: 'Ingresos'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        tooltip: {
            valueSuffix: ' USD'
        },
        legend: {
            layout: 'vertical',
            align: 'left',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: false
                },
                enableMouseTracking: true
            }
        },
        series: [{
            name: 'Ambato',
            data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
        }, {
            name: 'Cuenca',
            data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
        }, {
            name: 'Loja',
            data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]
        }, {
            name: 'Ibarra',
            data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
        }]
    });
});
		</script>
				<script type="text/javascript">
$(function () {
    $('#container3').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Total ingresos por ciudad'
        },
        subtitle: {
            text: 'Ciudad: Todas / Año: 2014'
        },
        xAxis: {
            categories: [
                'Ene',
                'Feb',
                'Mar',
                'Abr',
                'May',
                'Jun',
                'Jul',
                'Ago',
                'Sep',
                'Oct',
                'Nov',
                'Dic'
            ]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Ingresos'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>&nbsp; {point.y:.1f} USD</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
            	dataLabels: {
                    enabled: false
                },
                pointPadding: 0.2,
                borderWidth: 0
            },
        },
        series: [{
            name: 'Ambato',
            data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

        }, {
            name: 'Cuenca',
            data: [83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3]

        }, {
            name: 'Loja',
            data: [48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2]

        }, {
            name: 'Ibarra',
            data: [42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1]

        }]
    });
});
		</script>
<script src="<?php echo $this->basepath() . '/js/highcharts.js'?>"></script>
<script src="<?php echo $this->basepath() . '/js/modules/exporting.js'?>"></script>
