<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div id="map-canvas" style="width:1150px; height:500px;"></div>
        
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
<script>
    var map;
    var markers = [];
    var geocoder;
    
    function initialize() {

        geocoder = new google.maps.Geocoder();
        var lugar = new google.maps.LatLng(0.349688, -78.122566);
        var mapOptions = { zoom: 16, center: lugar };
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

        <?php foreach($this->parqueaderos as $parqueadero): ?>
            <?php if($parqueadero->getPar_latitud()!='' && $parqueadero->getPar_longitud()!=''): ?>
                var myLatLng = {lat: <?php echo $parqueadero->getPar_latitud() ?>, lng: <?php echo $parqueadero->getPar_longitud() ?>};

                var marker = new google.maps.Marker({
                    position: myLatLng,
                    map: map,
                    title: '<?php echo $parqueadero->getPar_id() ?>'
                });
            <?php endif; ?>
        <?php endforeach; ?>

    }
    
    function addMarker(location, map) {
          var marker = new google.maps.Marker({
            position: location,
            draggable: true,
            map: map
          });
         markers.push(marker);
    
         google.maps.event.addListener(marker, 'click', function(e) {
    
             var infowindow = new google.maps.InfoWindow({
                  content: '<div>'+$('#sec_nombre').val()+'</div>'+'<div>'+$('#sec_ubicacion').val()+'</div>'
              });
             
             infowindow.open(map,marker);
         });
    
         google.maps.event.addListener(marker, 'dragend', function (event) {
                $('#sec_latitud').val(this.getPosition().lat());
                $('#sec_longitud').val(this.getPosition().lng());
            });
         
        }
    
    function totalMarkers(){
          return markers.length;
    }

    // Sets the map on all markers in the array.
    function setAllMap(map) {
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(map);
      }
    }

    
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
