<div class="titulo-ventana"><i class="fa fa-gears fa-fw"></i> Par&aacute;metros - Listado Tipos de Veh&iacute;culos</div>
<hr class="hr-style" />

 <table class="table table-striped table-hover" style="font-size: 12px;" >
 <thead>
 <tr>
 	 <th width="7%">
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'tipovehiculo', 'action'=>'ingresar'));?>" class="btn btn-primary">
     	<i class="fa fa-plus-circle"></i> Nuevo</a>
 	 </th>
     <th>Descripci&oacute;n</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->vehiculos as $tipo_vehiculo) : ?>
 <tr>
 	 <td style=" background-color: #fff;">
 	 	<a class="btn btn-success" href="<?php echo $this->url('parametros', array('controller' => 'tipovehiculo', 'action' => 'editar', 'id' => $tipo_vehiculo->getTip_veh_id()))?>"><i class="fa fa-pencil"></i></a>
 	 	<a class="btn btn-danger" href="<?php echo $this->url('parametros', array('controller' => 'tipovehiculo', 'action' => 'eliminar', 'id' => $tipo_vehiculo->getTip_veh_id()))?>" onclick="return eliminarRegistro('<?php echo $tipo_vehiculo->getTip_veh_descripcion() ?>');"><i class="fa fa-trash-o"></i></a>
 	 </td>
 	 <td><?php echo $this->escapeHtml($tipo_vehiculo->getTip_veh_descripcion());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>