<?php echo $this->partial('partial/navegacion.phtml', $this->navegacion); ?>

<div class="row">
	<div class="col-xs-8">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-user"></i>
					<span>Perfil del cliente</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="card">
				
					<div class="media">
                      <a class="pull-left" href="#">
                        <img src="<?php echo $this->basepath() . '/img/avatar.jpg'?>" alt="..." class="thumbnail img-circle" style="min-width: 260px; max-width: 270px">
                      </a>
                      <div class="  ">
                            <h3 class="media-heading page-header"><b><?php echo $this->cliente->getUsu_nombre() . ' ' . $this->cliente->getUsu_apellido() ?></b></h3>
                            <p><span style="font-weight: 700;">Usuario: </span> <span><?php echo $this->cliente->getUsu_usuario()  ?></span><br /></p>
                            <p><span style="font-weight: 700;">Email: </span> <a href="#"><?php echo $this->cliente->getUsu_email()  ?></a><br /></p>
					       <p><span style="font-weight: 700;">C&oacute;digo Interno: </span> <span><?php echo $this->cliente->getUsu_clave()  ?></span> <br></p>
					       <p><span style="font-weight: 700;">M&oacute;vil: </span> <span><?php echo '( +' . $this->cliente->getCli_cod_pais() . ' )' . ' ( ' . $this->cliente->getCli_cod_ciudad() . ' ) ' . $this->cliente->getCli_movil()?></span> <br></p>
					       <p><span style="font-weight: 700;">Direcci&oacute;n: </span> <span><?php $direccion = $this->cliente->getCli_direccion(); if(!empty($direccion) && !is_null($direccion)): echo $direccion; else: echo '<span style="color:#CCCCCC; font-style:italic; ">No tiene informaci&oacute;n.</span>'; endif;  ?></span> <br></p>
					       <p><span style="font-weight: 700;">Saldo:</span> <span style="color:#ee9f1f; font-weight: 700;">$<?php echo $this->cliente->getCli_saldo()?></span> <br></p>
                      </div>
                    </div>
					
				</div>
			</div>
		</div>
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-dollar"></i>
					<span>Compras</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="card">
					<h4 class="page-header">Jonh Smith</h4>
					<h5 class="page-header">Manager</h5>
					<p>
						<span>+1 (123) 434-123445</span> <br>
						<a href="mailto:john@company.com">john@company.com</a>
					</p>
				</div>
				<div class="card address">
					<div class="vcard">
						<a href="#"><i class="fa fa-file"></i>.vCard</a>
					</div>
					<h4>Adress:</h4>
					<p>
						<span>123456, Silicon walley</span> <br>
						<span>str. Nonest. building 33</span>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-4">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-exchange"></i>
					<span>Usuarios permitidos para transferir</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="card">
					<h4 class="page-header">Jonh Smith</h4>
					<h5 class="page-header">Manager</h5>
					<p>
						<span>+1 (123) 434-123445</span> <br>
						<a href="mailto:john@company.com">john@company.com</a>
					</p>
				</div>
				<div class="card address">
					<div class="vcard">
						<a href="#"><i class="fa fa-file"></i>.vCard</a>
					</div>
					<h4>Adress:</h4>
					<p>
						<span>123456, Silicon walley</span> <br>
						<span>str. Nonest. building 33</span>
					</p>
				</div>
			</div>
		</div>
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-money"></i>
					<span>Recargas</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="card">
					<h4 class="page-header">Chuck Norris</h4>
					<h5 class="page-header">Designer</h5>
					<p>
						<span>+1 (123) 333-856823</span> <br>
						<a href="mailto:chuck@company.com">chuck@company.com</a>
					</p>
				</div>
				<div class="card address">
					<div class="vcard">
						<a href="#"><i class="fa fa-file"></i>.vCard</a>
					</div>
					<h4>Adress:</h4>
					<p>
						<span>123456, Silicon walley</span> <br>
						<span>str. Nonest. building 33</span>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
// Load OpenLayers library and create test map
function OpenLayersMap() {
	$.getScript('http://www.openlayers.org/api/OpenLayers.js', LoadTestMap);
}
$(document).ready(function () {
	// Load Google Map API and callback to OpenLayers
	$.getScript('http://maps.google.com/maps/api/js?sensor=false&callback=OpenLayersMap');
	// Add Drag-n-Drop feature
	WinMove();
});
</script>
